'use client'

/**
 * Campaigns CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: MCA
 * Entity: CAMPAIGN
 * Smart Code: HERA.CRM.MCA.ENTITY.CAMPAIGN.V1
 * Description: Outbound message campaigns with scheduling
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Send,
  Trash2,
  TrendingUp,
  Upload,
  X
} from 'lucide-react'

/**
 * Campaign Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface Campaign extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  name?: string
  segment_id?: string
  template_id?: string
  channel_mix?: string
  schedule?: string
  status?: string
  results?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA Campaign Smart Codes
 * Auto-generated from preset configuration
 */
const CAMPAIGN_SMART_CODES = {
  ENTITY: 'HERA.CRM.MCA.ENTITY.CAMPAIGN.V1',
  FIELD_NAME: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.NAME.V1',
  FIELD_SEGMENT_ID: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.SEGMENT_ID.V1',
  FIELD_TEMPLATE_ID: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.TEMPLATE_ID.V1',
  FIELD_CHANNEL_MIX: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.CHANNEL_MIX.V1',
  FIELD_SCHEDULE: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.SCHEDULE.V1',
  FIELD_STATUS: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.STATUS.V1',
  FIELD_RESULTS: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.RESULTS.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.CRM.MCA.EVENT.CAMPAIGN.V1.CREATED.V1',
  EVENT_UPDATED: 'HERA.CRM.MCA.EVENT.CAMPAIGN.V1.UPDATED.V1',
  EVENT_DELETED: 'HERA.CRM.MCA.EVENT.CAMPAIGN.V1.DELETED.V1'
} as const

/**
 * Campaigns Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function CampaignsPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedCampaigns, setSelectedCampaigns] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentCampaign, setCurrentCampaign] = useState<Campaign | null>(null)
  const [campaignToDelete, setCampaignToDelete] = useState<Campaign | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    name: '',
    segment_id: '',
    template_id: ''
  })

  // HERA Universal Entity Integration
  const campaignData = useUniversalEntity({
    entity_type: 'CAMPAIGN',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'name', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.NAME.V1', required: false },
      { name: 'segment_id', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.SEGMENT_ID.V1', required: false },
      { name: 'template_id', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.TEMPLATE_ID.V1', required: false },
      { name: 'channel_mix', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.CHANNEL_MIX.V1', required: false },
      { name: 'schedule', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.SCHEDULE.V1', required: false },
      { name: 'status', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.STATUS.V1', required: false },
      { name: 'results', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CAMPAIGN.V1.RESULTS.V1', required: false }
    ]
  })

  // Transform entities with business rule extensions
  const campaigns: Campaign[] = campaignData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      name: entity.dynamic_data?.find((d: any) => d.field_name === 'name')?.field_value_text || '',
      segment_id: entity.dynamic_data?.find((d: any) => d.field_name === 'segment_id')?.field_value_text || '',
      template_id: entity.dynamic_data?.find((d: any) => d.field_name === 'template_id')?.field_value_text || '',
      channel_mix: entity.dynamic_data?.find((d: any) => d.field_name === 'channel_mix')?.field_value_text || '',
      schedule: entity.dynamic_data?.find((d: any) => d.field_name === 'schedule')?.field_value_text || '',
      status: entity.dynamic_data?.find((d: any) => d.field_name === 'status')?.field_value_text || '',
      results: entity.dynamic_data?.find((d: any) => d.field_name === 'results')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total Campaigns',
      value: campaigns.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: Send
    },
    {
      title: 'Active Campaigns',
      value: campaigns.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: campaigns.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'Campaign Name', sortable: true },
    { key: 'name', label: 'Name', sortable: true },
    { key: 'segment_id', label: 'Segment id', sortable: true },
    { key: 'template_id', label: 'Template id', sortable: true },
    { key: 'channel_mix', label: 'Channel mix', sortable: true },
    { key: 'schedule', label: 'Schedule', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search Campaigns', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'name', label: 'Name', type: 'select', options: [
        { value: '', label: 'All Names' },
        ...Array.from(new Set(campaigns.map(item => item.name).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'segment_id', label: 'Segment Id', type: 'select', options: [
        { value: '', label: 'All Segment Ids' },
        ...Array.from(new Set(campaigns.map(item => item.segment_id).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddCampaign = async (campaignData: any) => {
    try {
      const result = await campaignData.create({
        entity_type: 'CAMPAIGN',
        entity_name: campaignData.entity_name,
        smart_code: CAMPAIGN_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, campaignData)

      // Emit creation event for audit trail
      await campaignData.emitEvent(CAMPAIGN_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: campaignData
      })

      setShowAddModal(false)
      console.log('✅ Campaign created successfully')
    } catch (error) {
      console.error('❌ Error adding campaign:', error)
    }
  }

  const handleEditCampaign = async (campaignData: any) => {
    if (!currentCampaign) return
    
    try {
      await campaignData.update(currentCampaign.entity_id!, {
        entity_name: campaignData.entity_name
      }, campaignData)

      // Emit update event
      await campaignData.emitEvent(CAMPAIGN_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentCampaign.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: campaignData
      })

      setShowEditModal(false)
      setCurrentCampaign(null)
      console.log('✅ Campaign updated successfully')
    } catch (error) {
      console.error('❌ Error updating campaign:', error)
    }
  }

  const handleDeleteCampaign = async () => {
    if (!campaignToDelete) return
    
    try {
      await campaignData.delete(campaignToDelete.entity_id!)

      // Emit deletion event
      await campaignData.emitEvent(CAMPAIGN_SMART_CODES.EVENT_DELETED, {
        entity_id: campaignToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: campaignToDelete.entity_name
      })

      setShowDeleteModal(false)
      setCampaignToDelete(null)
      console.log('✅ Campaign deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting campaign:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access Campaigns.</p>
      </div>
    )
  }

  if (campaignData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading Campaigns...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="Campaigns"
      subtitle={`${campaigns.length} total campaigns`}
      primaryColor="#6264a7"
      accentColor="#464775"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#6264a7' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={campaigns}
        columns={columns}
        selectedRows={selectedCampaigns}
        onRowSelect={setSelectedCampaigns}
        onRowClick={(campaign) => {
          setCurrentCampaign(campaign)
          setShowEditModal(true)
        }}
        showBulkActions={selectedCampaigns.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedCampaigns) {
                await campaignData.delete(id.toString())
              }
              setSelectedCampaigns([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(campaign) => (
          <MobileCard key={campaign.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{campaign.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentCampaign(campaign)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setCampaignToDelete(campaign)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Name:</span>{' '}
              {campaign.name || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Segment Id:</span>{' '}
              {campaign.segment_id || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Template Id:</span>{' '}
              {campaign.template_id || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Channel Mix:</span>{' '}
              {campaign.channel_mix || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {campaign.created_at ? new Date(campaign.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#6264a7' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <CampaignModal
          title="Add New Campaign"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddCampaign}
          dynamicFields={campaignData.dynamicFieldsConfig || []}
          businessRules={{"consent_validation":true,"schedule_optimization":true,"real_time_tracking":true,"audit_trail":true}}
        />
      )}

      {showEditModal && currentCampaign && (
        <CampaignModal
          title="Edit Campaign"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentCampaign(null)
          }}
          onSave={handleEditCampaign}
          initialData={currentCampaign}
          dynamicFields={campaignData.dynamicFieldsConfig || []}
          businessRules={{"consent_validation":true,"schedule_optimization":true,"real_time_tracking":true,"audit_trail":true}}
        />
      )}

      {showDeleteModal && campaignToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete Campaign</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{campaignToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setCampaignToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteCampaign}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise Campaign Modal Component
 * Enhanced with business rules and validation
 */
interface CampaignModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: Campaign
  dynamicFields: any[]
  businessRules: any
}

function CampaignModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: CampaignModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof Campaign] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'Campaign name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Campaign Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Name 
              </label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.name && (
                <p className="mt-1 text-sm text-red-600">{errors.name}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Segment Id 
              </label>
              <input
                type="text"
                value={formData.segment_id}
                onChange={(e) => setFormData({ ...formData, segment_id: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.segment_id ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.segment_id && (
                <p className="mt-1 text-sm text-red-600">{errors.segment_id}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Template Id 
              </label>
              <input
                type="text"
                value={formData.template_id}
                onChange={(e) => setFormData({ ...formData, template_id: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.template_id ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.template_id && (
                <p className="mt-1 text-sm text-red-600">{errors.template_id}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Channel Mix 
              </label>
              <input
                type="text"
                value={formData.channel_mix}
                onChange={(e) => setFormData({ ...formData, channel_mix: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.channel_mix ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.channel_mix && (
                <p className="mt-1 text-sm text-red-600">{errors.channel_mix}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Schedule 
              </label>
              <input
                type="text"
                value={formData.schedule}
                onChange={(e) => setFormData({ ...formData, schedule: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.schedule ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.schedule && (
                <p className="mt-1 text-sm text-red-600">{errors.schedule}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Status 
              </label>
              <input
                type="text"
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.status ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.status && (
                <p className="mt-1 text-sm text-red-600">{errors.status}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Results 
              </label>
              <input
                type="text"
                value={formData.results}
                onChange={(e) => setFormData({ ...formData, results: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.results ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.results && (
                <p className="mt-1 text-sm text-red-600">{errors.results}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#6264a7' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}