# Railway deployment configuration for WhatsApp integration

[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "whatsapp-webhook"
port = 3000

[services.whatsapp-webhook]
healthcheckPath = "/api/v1/whatsapp/webhook"
healthcheckInterval = 30
healthcheckTimeout = 10

# Environment variables (set via Railway CLI or dashboard)
# WHATSAPP_ACCESS_TOKEN
# WHATSAPP_PHONE_NUMBER_ID  
# WHATSAPP_WEBHOOK_VERIFY_TOKEN
# WHATSAPP_BUSINESS_ACCOUNT_ID
# DEFAULT_ORGANIZATION_ID
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY