'use client'

/**
 * Consent Preferences CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: MCA
 * Entity: CONSENT_PREF
 * Smart Code: HERA.CRM.MCA.ENTITY.CONSENT_PREF.V1
 * Description: GDPR consent management with legal basis
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Shield,
  Trash2,
  TrendingUp,
  Upload,
  X
} from 'lucide-react'

/**
 * Consent Preference Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface ConsentPreference extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  contact_id?: string
  purpose?: string
  status?: string
  legal_basis?: string
  source?: string
  evidence?: string
  expires_at?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA Consent Preference Smart Codes
 * Auto-generated from preset configuration
 */
const CONSENT_PREF_SMART_CODES = {
  ENTITY: 'HERA.CRM.MCA.ENTITY.CONSENT_PREF.V1',
  FIELD_CONTACT_ID: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.CONTACT_ID.V1',
  FIELD_PURPOSE: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.PURPOSE.V1',
  FIELD_STATUS: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.STATUS.V1',
  FIELD_LEGAL_BASIS: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.LEGAL_BASIS.V1',
  FIELD_SOURCE: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.SOURCE.V1',
  FIELD_EVIDENCE: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.EVIDENCE.V1',
  FIELD_EXPIRES_AT: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.EXPIRES_AT.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.CRM.MCA.EVENT.CONSENT_PREF.V1.CREATED.V1',
  EVENT_UPDATED: 'HERA.CRM.MCA.EVENT.CONSENT_PREF.V1.UPDATED.V1',
  EVENT_DELETED: 'HERA.CRM.MCA.EVENT.CONSENT_PREF.V1.DELETED.V1'
} as const

/**
 * Consent Preferences Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function Consent PreferencesPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedConsent Preferences, setSelectedConsent Preferences] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentConsent Preference, setCurrentConsent Preference] = useState<Consent Preference | null>(null)
  const [consent_prefToDelete, setConsent PreferenceToDelete] = useState<Consent Preference | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    contact_id: '',
    purpose: '',
    status: ''
  })

  // HERA Universal Entity Integration
  const consent_prefData = useUniversalEntity({
    entity_type: 'CONSENT_PREF',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'contact_id', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.CONTACT_ID.V1', required: false },
      { name: 'purpose', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.PURPOSE.V1', required: false },
      { name: 'status', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.STATUS.V1', required: false },
      { name: 'legal_basis', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.LEGAL_BASIS.V1', required: false },
      { name: 'source', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.SOURCE.V1', required: false },
      { name: 'evidence', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.EVIDENCE.V1', required: false },
      { name: 'expires_at', type: 'text', smart_code: 'HERA.CRM.MCA.DYN.CONSENT_PREF.V1.EXPIRES_AT.V1', required: false }
    ]
  })

  // Transform entities with business rule extensions
  const consent_prefs: Consent Preference[] = consent_prefData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      contact_id: entity.dynamic_data?.find((d: any) => d.field_name === 'contact_id')?.field_value_text || '',
      purpose: entity.dynamic_data?.find((d: any) => d.field_name === 'purpose')?.field_value_text || '',
      status: entity.dynamic_data?.find((d: any) => d.field_name === 'status')?.field_value_text || '',
      legal_basis: entity.dynamic_data?.find((d: any) => d.field_name === 'legal_basis')?.field_value_text || '',
      source: entity.dynamic_data?.find((d: any) => d.field_name === 'source')?.field_value_text || '',
      evidence: entity.dynamic_data?.find((d: any) => d.field_name === 'evidence')?.field_value_text || '',
      expires_at: entity.dynamic_data?.find((d: any) => d.field_name === 'expires_at')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total Consent Preferences',
      value: consent_prefs.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: Shield
    },
    {
      title: 'Active Consent Preferences',
      value: consent_prefs.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: consent_prefs.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'Consent Preference Name', sortable: true },
    { key: 'contact_id', label: 'Contact id', sortable: true },
    { key: 'purpose', label: 'Purpose', sortable: true },
    { key: 'status', label: 'Status', sortable: true },
    { key: 'legal_basis', label: 'Legal basis', sortable: true },
    { key: 'source', label: 'Source', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search Consent Preferences', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'contact_id', label: 'Contact Id', type: 'select', options: [
        { value: '', label: 'All Contact Ids' },
        ...Array.from(new Set(consent_prefs.map(item => item.contact_id).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'purpose', label: 'Purpose', type: 'select', options: [
        { value: '', label: 'All Purposes' },
        ...Array.from(new Set(consent_prefs.map(item => item.purpose).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddConsent Preference = async (consent_prefData: any) => {
    try {
      const result = await consent_prefData.create({
        entity_type: 'CONSENT_PREF',
        entity_name: consent_prefData.entity_name,
        smart_code: CONSENT_PREF_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, consent_prefData)

      // Emit creation event for audit trail
      await consent_prefData.emitEvent(CONSENT_PREF_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: consent_prefData
      })

      setShowAddModal(false)
      console.log('✅ Consent Preference created successfully')
    } catch (error) {
      console.error('❌ Error adding consent_pref:', error)
    }
  }

  const handleEditConsent Preference = async (consent_prefData: any) => {
    if (!currentConsent Preference) return
    
    try {
      await consent_prefData.update(currentConsent Preference.entity_id!, {
        entity_name: consent_prefData.entity_name
      }, consent_prefData)

      // Emit update event
      await consent_prefData.emitEvent(CONSENT_PREF_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentConsent Preference.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: consent_prefData
      })

      setShowEditModal(false)
      setCurrentConsent Preference(null)
      console.log('✅ Consent Preference updated successfully')
    } catch (error) {
      console.error('❌ Error updating consent_pref:', error)
    }
  }

  const handleDeleteConsent Preference = async () => {
    if (!consent_prefToDelete) return
    
    try {
      await consent_prefData.delete(consent_prefToDelete.entity_id!)

      // Emit deletion event
      await consent_prefData.emitEvent(CONSENT_PREF_SMART_CODES.EVENT_DELETED, {
        entity_id: consent_prefToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: consent_prefToDelete.entity_name
      })

      setShowDeleteModal(false)
      setConsent PreferenceToDelete(null)
      console.log('✅ Consent Preference deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting consent_pref:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access Consent Preferences.</p>
      </div>
    )
  }

  if (consent_prefData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading Consent Preferences...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="Consent Preferences"
      subtitle={`${consent_prefs.length} total consent_prefs`}
      primaryColor="#107c10"
      accentColor="#0b5a0b"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#107c10' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={consent_prefs}
        columns={columns}
        selectedRows={selectedConsent Preferences}
        onRowSelect={setSelectedConsent Preferences}
        onRowClick={(consent_pref) => {
          setCurrentConsent Preference(consent_pref)
          setShowEditModal(true)
        }}
        showBulkActions={selectedConsent Preferences.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedConsent Preferences) {
                await consent_prefData.delete(id.toString())
              }
              setSelectedConsent Preferences([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(consent_pref) => (
          <MobileCard key={consent_pref.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{consent_pref.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentConsent Preference(consent_pref)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setConsent PreferenceToDelete(consent_pref)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Contact Id:</span>{' '}
              {consent_pref.contact_id || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Purpose:</span>{' '}
              {consent_pref.purpose || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Status:</span>{' '}
              {consent_pref.status || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Legal Basis:</span>{' '}
              {consent_pref.legal_basis || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {consent_pref.created_at ? new Date(consent_pref.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#107c10' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <Consent PreferenceModal
          title="Add New Consent Preference"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddConsent Preference}
          dynamicFields={consent_prefData.dynamicFieldsConfig || []}
          businessRules={{"audit_trail":true,"gdpr_compliance":true,"requires_evidence":true}}
        />
      )}

      {showEditModal && currentConsent Preference && (
        <Consent PreferenceModal
          title="Edit Consent Preference"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentConsent Preference(null)
          }}
          onSave={handleEditConsent Preference}
          initialData={currentConsent Preference}
          dynamicFields={consent_prefData.dynamicFieldsConfig || []}
          businessRules={{"audit_trail":true,"gdpr_compliance":true,"requires_evidence":true}}
        />
      )}

      {showDeleteModal && consent_prefToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete Consent Preference</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{consent_prefToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setConsent PreferenceToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteConsent Preference}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise Consent Preference Modal Component
 * Enhanced with business rules and validation
 */
interface ConsentPreferenceModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: Consent Preference
  dynamicFields: any[]
  businessRules: any
}

function Consent PreferenceModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: Consent PreferenceModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof Consent Preference] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'Consent Preference name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Consent Preference Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Contact Id 
              </label>
              <input
                type="text"
                value={formData.contact_id}
                onChange={(e) => setFormData({ ...formData, contact_id: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.contact_id ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.contact_id && (
                <p className="mt-1 text-sm text-red-600">{errors.contact_id}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Purpose 
              </label>
              <input
                type="text"
                value={formData.purpose}
                onChange={(e) => setFormData({ ...formData, purpose: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.purpose ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.purpose && (
                <p className="mt-1 text-sm text-red-600">{errors.purpose}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Status 
              </label>
              <input
                type="text"
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.status ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.status && (
                <p className="mt-1 text-sm text-red-600">{errors.status}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Legal Basis 
              </label>
              <input
                type="text"
                value={formData.legal_basis}
                onChange={(e) => setFormData({ ...formData, legal_basis: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.legal_basis ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.legal_basis && (
                <p className="mt-1 text-sm text-red-600">{errors.legal_basis}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Source 
              </label>
              <input
                type="text"
                value={formData.source}
                onChange={(e) => setFormData({ ...formData, source: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.source ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.source && (
                <p className="mt-1 text-sm text-red-600">{errors.source}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Evidence 
              </label>
              <input
                type="text"
                value={formData.evidence}
                onChange={(e) => setFormData({ ...formData, evidence: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.evidence ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.evidence && (
                <p className="mt-1 text-sm text-red-600">{errors.evidence}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Expires At 
              </label>
              <input
                type="text"
                value={formData.expires_at}
                onChange={(e) => setFormData({ ...formData, expires_at: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.expires_at ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.expires_at && (
                <p className="mt-1 text-sm text-red-600">{errors.expires_at}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#107c10' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}