'use client'

/**
 * Inventory Dashboard
 * Generated by HERA Claude App Builder
 * 
 * Features:
 * ✅ Real-time KPI calculations
 * ✅ Mobile-first responsive layout
 * ✅ Interactive navigation cards
 * ✅ Performance optimized
 */

import React from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileCard } from '@/components/mobile/MobileCard'
import { useRouter } from 'next/navigation'
import { 
  Package, 
  MapPin, 
  TrendingUp, 
  AlertCircle,
  BarChart3,
  Grid,
  ArrowRightLeft,
  Plus
} from 'lucide-react'

export default function InventoryDashboard() {
  const router = useRouter()

  // KPI data - in production, this would come from HERA APIs
  const kpis = [
    { 
      title: 'Total Products', 
      value: '156', 
      change: '+5.2%',
      trend: 'up',
      icon: Package, 
      color: 'blue',
      onClick: () => router.push('/inventory/products')
    },
    { 
      title: 'Storage Locations', 
      value: '8', 
      change: '+1',
      trend: 'up',
      icon: MapPin, 
      color: 'green',
      onClick: () => router.push('/inventory/locations')
    },
    { 
      title: 'Stock Adjustments', 
      value: '23', 
      change: '+12%',
      trend: 'up',
      icon: TrendingUp, 
      color: 'yellow',
      onClick: () => router.push('/inventory/adjustments')
    },
    { 
      title: 'Low Stock Items', 
      value: '5', 
      change: '-38%',
      trend: 'down',
      icon: AlertCircle, 
      color: 'red',
      onClick: () => router.push('/inventory/products?filter=low-stock')
    }
  ]

  // Quick action cards
  const quickActions = [
    {
      title: 'Product Catalog',
      description: 'Manage products and specifications',
      icon: Package,
      color: 'blue',
      action: () => router.push('/inventory/products')
    },
    {
      title: 'Storage Locations', 
      description: 'Manage warehouses and locations',
      icon: MapPin,
      color: 'green',
      action: () => router.push('/inventory/locations')
    },
    {
      title: 'Stock Adjustments',
      description: 'Adjust inventory levels',
      icon: TrendingUp,
      color: 'yellow',
      action: () => router.push('/inventory/adjustments')
    },
    {
      title: 'Stock Transfers',
      description: 'Transfer between locations',
      icon: ArrowRightLeft,
      color: 'purple',
      action: () => router.push('/inventory/transfers')
    },
    {
      title: 'Reports',
      description: 'Analytics and reporting',
      icon: BarChart3,
      color: 'indigo',
      action: () => router.push('/inventory/reports')
    },
    {
      title: 'Categories',
      description: 'Product categorization',
      icon: Grid,
      color: 'teal',
      action: () => router.push('/inventory/categories')
    }
  ]

  const getColorClasses = (color: string) => ({
    bg: `bg-${color}-500`,
    text: `text-${color}-600`,
    hover: `hover:bg-${color}-700`
  })

  return (
    <MobilePageLayout
      title="Inventory Dashboard"
      subtitle="Smart inventory management overview"
      primaryColor="#3B82F6"
      showBackButton={false}
    >
      {/* Welcome Section - Mobile optimized */}
      <div className="md:hidden bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 mb-6">
        <h2 className="text-xl font-bold text-gray-900 mb-2">Welcome Back!</h2>
        <p className="text-gray-600">Your inventory is running smoothly today.</p>
      </div>

      {/* KPI Grid - Responsive design */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard 
            key={index} 
            className="p-4 hover:shadow-md transition-shadow cursor-pointer active:scale-95"
            onClick={kpi.onClick}
          >
            <div className="text-center">
              <kpi.icon className={`h-8 w-8 mx-auto mb-2 text-${kpi.color}-500`} />
              <p className="text-lg md:text-2xl font-bold">{kpi.value}</p>
              <p className="text-xs text-gray-600 mb-1">{kpi.title}</p>
              <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                {kpi.change}
              </p>
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Quick Actions - Mobile-first grid */}
      <div className="mb-6">
        <h3 className="text-lg font-semibold mb-4 text-gray-900">Quick Actions</h3>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {quickActions.map((action, index) => (
            <MobileCard 
              key={index} 
              className="p-6 hover:shadow-md transition-shadow cursor-pointer active:scale-95"
              onClick={action.action}
            >
              <div className="flex items-start space-x-4">
                <div className={`p-3 rounded-xl bg-${action.color}-100`}>
                  <action.icon className={`h-6 w-6 text-${action.color}-600`} />
                </div>
                <div className="flex-1 min-w-0">
                  <h4 className="font-semibold text-gray-900 mb-1">{action.title}</h4>
                  <p className="text-sm text-gray-600">{action.description}</p>
                </div>
              </div>
            </MobileCard>
          ))}
        </div>
      </div>

      {/* Recent Activity - Responsive layout */}
      <div className="mb-6">
        <h3 className="text-lg font-semibold mb-4 text-gray-900">Recent Activity</h3>
        <MobileCard className="p-6">
          <div className="space-y-4">
            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-green-500 rounded-full"></div>
              <p className="text-sm text-gray-700">
                <span className="font-medium">Product "Wireless Headphones"</span> stock adjusted (+50 units)
              </p>
              <span className="text-xs text-gray-500 ml-auto">2 min ago</span>
            </div>
            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-blue-500 rounded-full"></div>
              <p className="text-sm text-gray-700">
                <span className="font-medium">New location</span> "Warehouse B" added
              </p>
              <span className="text-xs text-gray-500 ml-auto">1 hour ago</span>
            </div>
            <div className="flex items-center space-x-3">
              <div className="w-2 h-2 bg-yellow-500 rounded-full"></div>
              <p className="text-sm text-gray-700">
                <span className="font-medium">Low stock alert</span> for "USB Cables"
              </p>
              <span className="text-xs text-gray-500 ml-auto">3 hours ago</span>
            </div>
          </div>
        </MobileCard>
      </div>

      {/* Mobile-specific bottom spacing */}
      <div className="h-24 md:h-0" />
    </MobilePageLayout>
  )
}