#!/bin/bash

echo "📋 Checking Railway Logs for WhatsApp Errors"
echo "==========================================="
echo ""
echo "Run this command to see recent WhatsApp-related logs:"
echo ""
echo "railway logs | grep -A 5 -B 5 -i 'whatsapp.*error\\|failed to store\\|error storing'"
echo ""
echo "Or for all WhatsApp activity:"
echo ""
echo "railway logs | grep -i whatsapp | tail -50"
echo ""
echo "Look for:"
echo "- 'Error storing message'"
echo "- 'Failed to store WhatsApp message'"
echo "- Any database errors"
echo ""
echo "Once the debug endpoint deploys, test it:"
echo "curl https://heraerp.com/api/v1/whatsapp/debug"