# railway.toml - Railway deployment configuration per comprehensive healthcheck docs

[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
# Optimized Next.js server with faster startup (Golden Rule #1)
startCommand = "npm start"

# Robust healthcheck configuration (Golden Rule #4)
healthcheckPath = "/api/health"
healthcheckTimeout = 600
healthcheckInterval = 30
gracePeriod = 60

# Enhanced restart policy for large applications
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# ---- Environment-specific overrides ----
# Production environment gets full healthcheck
[environments.production.deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 600
healthcheckInterval = 30

# Development environment disables healthcheck for faster iteration
[environments.develop.deploy]
healthcheckPath = ""
