[build]
builder = "nixpacks"
buildCommand = "npm run build:railway"

[build.environment]
NODE_VERSION = "20.18.0"
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
NPM_CONFIG_LOGLEVEL = "error"
SKIP_ENV_VALIDATION = "true"
RAILWAY_ENVIRONMENT = "true"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production"