cat > railway.toml <<'TOML'
[build]
builder = "nixpacks"
buildCommand = "npm ci && npm run build"

[build.env]
NPM_CONFIG_CACHE = "/opt/railway/.npm"
NPM_CONFIG_PREFER_OFFLINE = "true"
NPM_CONFIG_PROGRESS = "false"
NPM_CONFIG_FUND = "false"
NPM_CONFIG_AUDIT = "false"
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
NODE_OPTIONS = "--max-old-space-size=8192"
CI = "true"
SKIP_ENV_VALIDATION = "true"
NIXPACKS_NODE_VERSION = "20.12.2"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 300
healthcheckDelay = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "npm run start"

[deploy.env]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
TOML
