[build]
builder = "nixpacks"
buildCommand = "npm ci --legacy-peer-deps && npm run build:railway"

[build.environment]
NODE_VERSION = "20.18.0"
NODE_OPTIONS = "--max-old-space-size=4096"
NEXT_TELEMETRY_DISABLED = "1"
NPM_CONFIG_LOGLEVEL = "error"
SKIP_ENV_VALIDATION = "true"
RAILWAY_ENVIRONMENT = "true"
NEXT_PUBLIC_SUPABASE_URL = "https://dummy.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "dummy-anon-key"
SUPABASE_SERVICE_ROLE_KEY = "dummy-service-key"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.environment]
NODE_ENV = "production"