#!/bin/bash

# Define truly public marketing/landing pages that should KEEP changes
PUBLIC_PAGES=(
  "src/app/page.tsx"
  "src/app/layout.tsx"
  "src/app/globals.css"
  "src/app/not-found.tsx"
  "src/app/error.tsx"
  "src/app/auth/"
  "src/app/\(auth\)/"
  "src/app/blog/"
  "src/app/contact/"
  "src/app/pricing/"
  "src/app/pricing-request/"
  "src/app/partners/"
  "src/app/solutions/"
  "src/app/landing/"
  "src/app/get-started/"
  "src/app/free-guide/"
  "src/app/terms/"
  "src/app/policy/"
  "src/app/demo/"
  "src/app/book-a-meeting/"
  "src/app/thank-you/"
  "src/app/how-it-works/"
  "src/app/features/"
  "src/app/discover/"
  "src/app/apps/"
  "src/app/components/Footer"
  "src/app/components/Navbar"
)

# Define app-specific pages that should be ROLLED BACK
APP_PAGES=(
  "src/app/salon/"
  "src/app/salon-data/"
  "src/app/finance/"
  "src/app/financial/"
  "src/app/isp/"
  "src/app/civicflow/"
  "src/app/crm/"
  "src/app/furniture/"
  "src/app/franchise/"
  "src/app/development/"
  "src/app/whatsapp"
  "src/app/mcp-"
  "src/app/enterprise/"
  "src/app/budgeting/"
  "src/app/calendar/"
  "src/app/dashboard/"
  "src/app/dashboards/"
  "src/app/debug-auth/"
  "src/app/demo-init/"
  "src/app/hairtalkz/"
  "src/app/learning/"
  "src/app/org/"
  "src/app/readiness-"
  "src/app/runs/"
  "src/app/settings/"
  "src/app/sql-"
  "src/app/tasks/"
  "src/app/test-"
  "src/app/trial-balance/"
  "src/app/universal-ui/"
  "src/app/validate/"
  "src/app/auto-journal/"
  "src/app/admin/"
  "src/app/docs/"
)

echo "Files to rollback:"
for pattern in "${APP_PAGES[@]}"; do
  git diff --name-only | grep "^$pattern" || true
done | sort -u
