/**
 * Products Page
 * 
 * Generated by HERA Hook-Driven Module Generator
 * Uses HERAMasterDataTemplate for consistent enterprise UX
 */

'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useProductss, useProductsMutations } from '@/lib/hooks/useProductss'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import HERAMasterDataTemplate from '@/components/hera/HERAMasterDataTemplate'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { 
  Search, 
  Plus, 
  Package,
  Mail,
  Phone, 
  Edit,
  Trash2,
  Loader2,
  RefreshCw
} from 'lucide-react'

// Products form configuration using HERAMasterDataTemplate patterns
const PRODUCT_SECTIONS = [
  {
    id: 'basic',
    label: 'Basic Information',
    icon: Package,
    required: true,
    description: 'Enter basic products information and categorization'
  },
  {
    id: 'contact',
    label: 'Contact Details',
    icon: Mail,
    required: false,
    description: 'Contact information and communication preferences'
  },
  {
    id: 'business',
    label: 'Business Data',
    icon: Search,
    required: false,
    description: 'Business-specific fields and classifications'
  }
]

const PRODUCT_FIELDS = [
  {
    id: 'entity_name',
    label: 'Products Name',
    type: 'text' as const,
    required: true,
    placeholder: 'Enter products name',
    section: 'basic',
    validation: (value: string) => {
      return !value.trim() ? 'Name is required' : null
    }
  },
  {
    id: 'entity_code',
    label: 'Products Code',
    type: 'text' as const,
    required: true,
    placeholder: 'Auto-generated from name',
    section: 'basic'
  },
  {
    id: 'email',
    label: 'Email Address',
    type: 'email' as const,
    required: false,
    placeholder: 'contact@example.com',
    section: 'contact',
    validation: (value: string) => {
      if (!value) return null
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
      return !emailRegex.test(value) ? 'Please enter a valid email address' : null
    }
  },
  {
    id: 'phone',
    label: 'Phone Number',
    type: 'phone' as const,
    required: false,
    placeholder: '+1 (555) 123-4567',
    section: 'contact'
  }
]

export default function ProductsPage() {
  const router = useRouter()
  const { user, organization, isAuthenticated } = useHERAAuth()
  const [searchTerm, setSearchTerm] = useState('')
  const [showCreateForm, setShowCreateForm] = useState(false)

  // Use the generated hooks
  const { 
    productss, 
    loading, 
    error, 
    refetch 
  } = useProductss({
    search: searchTerm,
    limit: 50,
    offset: 0
  })

  const { 
    createProducts, 
    updateProducts, 
    deleteProducts 
  } = useProductsMutations()

  // Authentication checks
  if (!isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Alert>
          <AlertDescription>Please log in to access products management.</AlertDescription>
        </Alert>
      </div>
    )
  }

  if (!organization?.id) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Alert>
          <AlertDescription>No organization context available.</AlertDescription>
        </Alert>
      </div>
    )
  }

  // Handle create form submission using HERAMasterDataTemplate
  const handleCreateProducts = async (formData: Record<string, any>) => {
    // Generate HERA DNA smart code
    const smartCode = `HERA.RETAIL.PRODUCT.${formData.entity_code || 'ENTITY'}.v1`
    
    // Prepare dynamic fields from form data
    const dynamicFields = []
    
    if (formData.email) {
      dynamicFields.push({
        field_name: 'email',
        field_type: 'email',
        field_value_text: formData.email,
        smart_code: `HERA.RETAIL.PRODUCT.DYN.EMAIL.v1`
      })
    }
    
    if (formData.phone) {
      dynamicFields.push({
        field_name: 'phone',
        field_type: 'phone',
        field_value_text: formData.phone,
        smart_code: `HERA.RETAIL.PRODUCT.DYN.PHONE.v1`
      })
    }

    // Create entity using hook
    await createProducts({
      entity_name: formData.entity_name,
      dynamic_fields: {
        email: formData.email,
        phone: formData.phone
      }
    })
    
    // Refresh list and close form
    await refetch()
    setShowCreateForm(false)
  }

  const filteredProductss = productss?.filter(item => 
    item.entity_name?.toLowerCase().includes(searchTerm.toLowerCase())
  ) || []

  // Show create form using HERAMasterDataTemplate
  if (showCreateForm) {
    return (
      <HERAMasterDataTemplate
        entityType="products"
        entityLabel="Products"
        sections={PRODUCT_SECTIONS}
        fields={PRODUCT_FIELDS}
        backUrl="/retail/products"
        onSubmit={handleCreateProducts}
      />
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      {/* Mobile header - following HERA mobile-first standards */}
      <div className="h-11 bg-gradient-to-b from-black/20 to-transparent md:hidden" />
      
      <div className="md:hidden sticky top-0 z-50 bg-white border-b border-gray-200">
        <div className="flex items-center justify-between p-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center">
              <Package className="w-5 h-5" style={{ color: '#10B981' }} />
            </div>
            <div>
              <h1 className="text-lg font-bold text-gray-900">Productss</h1>
              <p className="text-xs text-gray-600">HERA {config.moduleName.toUpperCase()}</p>
            </div>
          </div>
          <button 
            onClick={() => setShowCreateForm(true)}
            className="min-w-[44px] min-h-[44px] rounded-full bg-blue-100 flex items-center justify-center active:scale-95"
          >
            <Plus className="w-5 h-5 text-blue-600" />
          </button>
        </div>
      </div>

      {/* Desktop header */}
      <div className="hidden md:block mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Productss</h1>
            <p className="text-gray-600">Product catalog with inventory integration</p>
          </div>
          <div className="flex items-center gap-3">
            <Button
              onClick={() => setShowCreateForm(true)}
              className="flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              New Products
            </Button>
          </div>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="mb-6 flex items-center gap-4">
        <div className="flex-1">
          <Input
            placeholder="Search productss..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="max-w-md"
          />
        </div>
        <Button variant="outline" onClick={refetch}>
          <RefreshCw className="w-4 h-4 mr-2" />
          Refresh
        </Button>
      </div>

      {/* Content */}
      {loading ? (
        <div className="text-center py-8">
          <div className="text-gray-500">Loading productss...</div>
        </div>
      ) : error ? (
        <Alert className="mb-6">
          <AlertDescription>
            Error loading productss: {error.message}
          </AlertDescription>
        </Alert>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
          {filteredProductss.map((products) => (
            <Card
              key={products.entity_id}
              className="cursor-pointer hover:shadow-lg transition-shadow"
              onClick={() => router.push(`/retail/products/${products.entity_id}`)}
            >
              <CardHeader>
                <div className="flex items-center gap-2 mb-2">
                  <Package className="w-5 h-5" style={{ color: '#10B981' }} />
                  <Badge variant="outline" className="text-xs">
                    {products.smart_code}
                  </Badge>
                </div>
                <CardTitle className="text-lg">{products.entity_name}</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-sm text-gray-600 space-y-1">
                  <div>ID: {products.entity_id}</div>
                  <div>Updated: {new Date(products.updated_at).toLocaleDateString()}</div>
                  {products.dynamic_fields?.email && (
                    <div>Email: {products.dynamic_fields.email.field_value_text}</div>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* Empty State */}
      {!loading && !error && filteredProductss.length === 0 && (
        <div className="text-center py-12">
          <div className="w-16 h-16 rounded-xl bg-gray-100 flex items-center justify-center mx-auto mb-4">
            <Package className="w-8 h-8 text-gray-400" />
          </div>
          <div className="text-gray-500 mb-4">No productss found</div>
          <Button onClick={() => setShowCreateForm(true)}>
            <Plus className="w-4 h-4 mr-2" />
            Create your first products
          </Button>
        </div>
      )}

      {/* Mobile bottom spacing */}
      <div className="h-24 md:h-0" />
    </div>
  )
}
