/**
 * HERA CRM Smart Code Registry
 * Smart Code: HERA.CRM.CORE.REGISTRY.SMART_CODES.V1
 * 
 * Comprehensive smart code definitions for CRM entities, dynamic fields, and relationships
 * Following Sacred Six architecture with complete organization_id isolation
 */

// CRM Entity Smart Codes
export const CRM_ENTITY_CODES = {
  // Core CRM Entities
  ACCOUNT: 'HERA.CRM.CORE.ENTITY.ACCOUNT.V1',
  CONTACT: 'HERA.CRM.CORE.ENTITY.CONTACT.V1', 
  LEAD: 'HERA.CRM.CORE.ENTITY.LEAD.V1',
  OPPORTUNITY: 'HERA.CRM.PIPELINE.ENTITY.OPPORTUNITY.V1',
  ACTIVITY: 'HERA.CRM.ACTIVITY.ENTITY.LOG.V1',
  TASK: 'HERA.CRM.ACTIVITY.ENTITY.TASK.V1',
  PRODUCT: 'HERA.CRM.CATALOG.ENTITY.PRODUCT.V1',
  QUOTE: 'HERA.CRM.SALES.ENTITY.QUOTE.V1',
  TERRITORY: 'HERA.CRM.CORE.ENTITY.TERRITORY.V1',
  CAMPAIGN: 'HERA.CRM.MARKETING.ENTITY.CAMPAIGN.V1'
} as const

// CRM Dynamic Field Smart Codes
export const CRM_DYNAMIC_FIELD_CODES = {
  // Account Fields
  ACCOUNT_INDUSTRY: 'HERA.CRM.CORE.DYN.ACCOUNT.INDUSTRY.V1',
  ACCOUNT_REVENUE: 'HERA.CRM.CORE.DYN.ACCOUNT.ANNUAL_REVENUE.V1',
  ACCOUNT_EMPLOYEES: 'HERA.CRM.CORE.DYN.ACCOUNT.EMPLOYEE_COUNT.V1',
  ACCOUNT_WEBSITE: 'HERA.CRM.CORE.DYN.ACCOUNT.WEBSITE.V1',
  ACCOUNT_TYPE: 'HERA.CRM.CORE.DYN.ACCOUNT.TYPE.V1',
  ACCOUNT_RATING: 'HERA.CRM.CORE.DYN.ACCOUNT.RATING.V1',
  
  // Contact Fields
  CONTACT_EMAIL: 'HERA.CRM.CORE.DYN.CONTACT.EMAIL.V1',
  CONTACT_PHONE: 'HERA.CRM.CORE.DYN.CONTACT.PHONE.V1',
  CONTACT_MOBILE: 'HERA.CRM.CORE.DYN.CONTACT.MOBILE.V1',
  CONTACT_TITLE: 'HERA.CRM.CORE.DYN.CONTACT.JOB_TITLE.V1',
  CONTACT_DEPARTMENT: 'HERA.CRM.CORE.DYN.CONTACT.DEPARTMENT.V1',
  CONTACT_BIRTHDAY: 'HERA.CRM.CORE.DYN.CONTACT.BIRTHDAY.V1',
  CONTACT_LINKEDIN: 'HERA.CRM.CORE.DYN.CONTACT.LINKEDIN.V1',
  CONTACT_ROLE: 'HERA.CRM.CORE.DYN.CONTACT.ROLE.V1', // Decision Maker, Influencer, etc.
  
  // Lead Fields
  LEAD_SOURCE: 'HERA.CRM.LEAD.DYN.SOURCE.V1',
  LEAD_STATUS: 'HERA.CRM.LEAD.DYN.STATUS.V1', 
  LEAD_SCORE: 'HERA.CRM.LEAD.DYN.SCORE.V1',
  LEAD_QUALIFICATION: 'HERA.CRM.LEAD.DYN.QUALIFICATION.V1',
  LEAD_COMPANY: 'HERA.CRM.LEAD.DYN.COMPANY.V1',
  LEAD_BUDGET: 'HERA.CRM.LEAD.DYN.BUDGET.V1',
  LEAD_TIMELINE: 'HERA.CRM.LEAD.DYN.TIMELINE.V1',
  
  // Opportunity Fields
  OPP_STAGE: 'HERA.CRM.PIPELINE.DYN.STAGE.V1',
  OPP_AMOUNT: 'HERA.CRM.PIPELINE.DYN.AMOUNT.V1',
  OPP_PROBABILITY: 'HERA.CRM.PIPELINE.DYN.PROBABILITY.V1',
  OPP_CLOSE_DATE: 'HERA.CRM.PIPELINE.DYN.CLOSE_DATE.V1',
  OPP_SOURCE: 'HERA.CRM.PIPELINE.DYN.SOURCE.V1',
  OPP_TYPE: 'HERA.CRM.PIPELINE.DYN.TYPE.V1', // New Business, Existing Business, Renewal
  OPP_FORECAST_CATEGORY: 'HERA.CRM.PIPELINE.DYN.FORECAST_CATEGORY.V1',
  OPP_COMPETITORS: 'HERA.CRM.PIPELINE.DYN.COMPETITORS.V1',
  OPP_NEXT_STEP: 'HERA.CRM.PIPELINE.DYN.NEXT_STEP.V1',
  
  // Activity Fields
  ACTIVITY_TYPE: 'HERA.CRM.ACTIVITY.DYN.TYPE.V1', // Call, Email, Meeting, Task
  ACTIVITY_DIRECTION: 'HERA.CRM.ACTIVITY.DYN.DIRECTION.V1', // Inbound, Outbound
  ACTIVITY_OUTCOME: 'HERA.CRM.ACTIVITY.DYN.OUTCOME.V1',
  ACTIVITY_DURATION: 'HERA.CRM.ACTIVITY.DYN.DURATION.V1',
  ACTIVITY_LOCATION: 'HERA.CRM.ACTIVITY.DYN.LOCATION.V1',
  ACTIVITY_ATTENDEES: 'HERA.CRM.ACTIVITY.DYN.ATTENDEES.V1',
  
  // Task Fields
  TASK_DUE_DATE: 'HERA.CRM.ACTIVITY.DYN.TASK.DUE_DATE.V1',
  TASK_PRIORITY: 'HERA.CRM.ACTIVITY.DYN.TASK.PRIORITY.V1',
  TASK_STATUS: 'HERA.CRM.ACTIVITY.DYN.TASK.STATUS.V1',
  TASK_OWNER: 'HERA.CRM.ACTIVITY.DYN.TASK.OWNER.V1',
  TASK_REMINDER: 'HERA.CRM.ACTIVITY.DYN.TASK.REMINDER.V1'
} as const

// CRM Relationship Smart Codes
export const CRM_RELATIONSHIP_CODES = {
  // Core Relationships
  CONTACT_OF_ACCOUNT: 'HERA.CRM.CORE.REL.CONTACT_OF.ACCOUNT.V1',
  OPPORTUNITY_OF_ACCOUNT: 'HERA.CRM.PIPELINE.REL.OPP_OF.ACCOUNT.V1',
  OPPORTUNITY_OF_CONTACT: 'HERA.CRM.PIPELINE.REL.OPP_OF.CONTACT.V1',
  ACTIVITY_OF_ACCOUNT: 'HERA.CRM.ACTIVITY.REL.OF_ACCOUNT.V1',
  ACTIVITY_OF_CONTACT: 'HERA.CRM.ACTIVITY.REL.OF_CONTACT.V1',
  ACTIVITY_OF_OPPORTUNITY: 'HERA.CRM.ACTIVITY.REL.OF_OPPORTUNITY.V1',
  TASK_OF_ACCOUNT: 'HERA.CRM.ACTIVITY.REL.TASK_OF.ACCOUNT.V1',
  TASK_OF_CONTACT: 'HERA.CRM.ACTIVITY.REL.TASK_OF.CONTACT.V1',
  TASK_OF_OPPORTUNITY: 'HERA.CRM.ACTIVITY.REL.TASK_OF.OPPORTUNITY.V1',
  
  // Lead Relationships
  LEAD_CONVERTED_TO_ACCOUNT: 'HERA.CRM.LEAD.REL.CONVERTED_TO.ACCOUNT.V1',
  LEAD_CONVERTED_TO_CONTACT: 'HERA.CRM.LEAD.REL.CONVERTED_TO.CONTACT.V1',
  LEAD_CONVERTED_TO_OPPORTUNITY: 'HERA.CRM.LEAD.REL.CONVERTED_TO.OPPORTUNITY.V1',
  
  // Sales Relationships
  QUOTE_OF_OPPORTUNITY: 'HERA.CRM.SALES.REL.QUOTE_OF.OPPORTUNITY.V1',
  QUOTE_LINE_OF_QUOTE: 'HERA.CRM.SALES.REL.LINE_OF.QUOTE.V1',
  PRODUCT_OF_QUOTE_LINE: 'HERA.CRM.SALES.REL.PRODUCT_OF.QUOTE_LINE.V1',
  
  // Territory & Assignment
  ACCOUNT_IN_TERRITORY: 'HERA.CRM.TERRITORY.REL.ACCOUNT_IN.TERRITORY.V1',
  OPPORTUNITY_IN_TERRITORY: 'HERA.CRM.TERRITORY.REL.OPP_IN.TERRITORY.V1',
  USER_OWNS_TERRITORY: 'HERA.CRM.TERRITORY.REL.USER_OWNS.TERRITORY.V1',
  
  // Campaign Relationships
  LEAD_FROM_CAMPAIGN: 'HERA.CRM.MARKETING.REL.LEAD_FROM.CAMPAIGN.V1',
  CONTACT_IN_CAMPAIGN: 'HERA.CRM.MARKETING.REL.CONTACT_IN.CAMPAIGN.V1'
} as const

// CRM Transaction Smart Codes
export const CRM_TRANSACTION_CODES = {
  // Lead Lifecycle
  LEAD_CREATED: 'HERA.CRM.LEAD.TXN.CREATED.V1',
  LEAD_QUALIFIED: 'HERA.CRM.LEAD.TXN.QUALIFIED.V1',
  LEAD_CONVERTED: 'HERA.CRM.LEAD.TXN.CONVERTED.V1',
  LEAD_DISQUALIFIED: 'HERA.CRM.LEAD.TXN.DISQUALIFIED.V1',
  
  // Opportunity Lifecycle
  OPPORTUNITY_CREATED: 'HERA.CRM.PIPELINE.TXN.OPP_CREATED.V1',
  OPPORTUNITY_STAGE_CHANGE: 'HERA.CRM.PIPELINE.TXN.STAGE_CHANGE.V1',
  OPPORTUNITY_WON: 'HERA.CRM.PIPELINE.TXN.OPP_WON.V1',
  OPPORTUNITY_LOST: 'HERA.CRM.PIPELINE.TXN.OPP_LOST.V1',
  OPPORTUNITY_REOPEN: 'HERA.CRM.PIPELINE.TXN.OPP_REOPEN.V1',
  
  // Activity Logging
  ACTIVITY_LOGGED: 'HERA.CRM.ACTIVITY.TXN.LOGGED.V1',
  TASK_CREATED: 'HERA.CRM.ACTIVITY.TXN.TASK_CREATED.V1',
  TASK_COMPLETED: 'HERA.CRM.ACTIVITY.TXN.TASK_COMPLETED.V1',
  
  // Sales Process
  QUOTE_CREATED: 'HERA.CRM.SALES.TXN.QUOTE_CREATED.V1',
  QUOTE_SENT: 'HERA.CRM.SALES.TXN.QUOTE_SENT.V1',
  QUOTE_ACCEPTED: 'HERA.CRM.SALES.TXN.QUOTE_ACCEPTED.V1',
  QUOTE_REJECTED: 'HERA.CRM.SALES.TXN.QUOTE_REJECTED.V1',
  
  // Assignment & Ownership
  OWNERSHIP_CHANGED: 'HERA.CRM.CORE.TXN.OWNERSHIP_CHANGED.V1',
  TERRITORY_ASSIGNED: 'HERA.CRM.TERRITORY.TXN.ASSIGNED.V1'
} as const

// CRM Status and Classification Values
export const CRM_STATUS_VALUES = {
  // Lead Status
  LEAD_STATUS: {
    NEW: 'New',
    CONTACTED: 'Contacted',
    QUALIFIED: 'Qualified',
    UNQUALIFIED: 'Unqualified',
    CONVERTED: 'Converted',
    NURTURING: 'Nurturing'
  },
  
  // Opportunity Stages (Configurable per organization)
  OPPORTUNITY_STAGES: {
    PROSPECTING: 'Prospecting',
    QUALIFICATION: 'Qualification', 
    NEEDS_ANALYSIS: 'Needs Analysis',
    VALUE_PROPOSITION: 'Value Proposition',
    PROPOSAL: 'Proposal',
    NEGOTIATION: 'Negotiation',
    CLOSED_WON: 'Closed Won',
    CLOSED_LOST: 'Closed Lost'
  },
  
  // Activity Types
  ACTIVITY_TYPES: {
    CALL: 'Call',
    EMAIL: 'Email',
    MEETING: 'Meeting',
    TASK: 'Task',
    NOTE: 'Note',
    SMS: 'SMS',
    SOCIAL: 'Social Media'
  },
  
  // Task Priority
  TASK_PRIORITY: {
    LOW: 'Low',
    NORMAL: 'Normal', 
    HIGH: 'High',
    URGENT: 'Urgent'
  },
  
  // Contact Roles
  CONTACT_ROLES: {
    DECISION_MAKER: 'Decision Maker',
    INFLUENCER: 'Influencer',
    USER: 'User',
    CHAMPION: 'Champion',
    BLOCKER: 'Blocker',
    GATEKEEPER: 'Gatekeeper'
  }
} as const

// CRM Smart Code Validation
export function validateCRMSmartCode(smartCode: string): boolean {
  const crmPattern = /^HERA\.CRM\.[A-Z]+\.[A-Z]+\.[A-Z_]+\.V\d+$/
  return crmPattern.test(smartCode)
}

// Get all CRM smart codes for validation
export function getAllCRMSmartCodes(): string[] {
  return [
    ...Object.values(CRM_ENTITY_CODES),
    ...Object.values(CRM_DYNAMIC_FIELD_CODES),
    ...Object.values(CRM_RELATIONSHIP_CODES),
    ...Object.values(CRM_TRANSACTION_CODES)
  ]
}

// CRM Entity Type Definitions
export type CRMEntityType = keyof typeof CRM_ENTITY_CODES
export type CRMDynamicField = keyof typeof CRM_DYNAMIC_FIELD_CODES  
export type CRMRelationship = keyof typeof CRM_RELATIONSHIP_CODES
export type CRMTransaction = keyof typeof CRM_TRANSACTION_CODES