'use client'

/**
 * Opportunities CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: CRM
 * Entity: OPPORTUNITY
 * Smart Code: HERA.CRM.PIPELINE.ENTITY.OPPORTUNITY.V1
 * Description: Sales opportunities and deals in pipeline
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  TrendingUp,
  Plus,
  Edit,
  Trash2,
  X,
  Save,
  Eye,
  Download,
  Upload,
  Search,
  Filter,
  MoreVertical,
  AlertCircle,
  CheckCircle,
  Clock
} from 'lucide-react'

/**
 * Opportunity Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface Opportunity extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  account?: string
  contact?: string
  value?: number
  stage?: string
  probability?: number
  close_date?: string
  owner?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  approval_status?: "pending" | "approved" | "rejected"
  workflow_stage?: string
}

/**
 * HERA Opportunity Smart Codes
 * Auto-generated from preset configuration
 */
const OPPORTUNITY_SMART_CODES = {
  ENTITY: 'HERA.CRM.PIPELINE.ENTITY.OPPORTUNITY.V1',
  FIELD_ACCOUNT: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.ACCOUNT.V1',
  FIELD_CONTACT: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.CONTACT.V1',
  FIELD_VALUE: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.VALUE.V1',
  FIELD_STAGE: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.STAGE.V1',
  FIELD_PROBABILITY: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.PROBABILITY.V1',
  FIELD_CLOSE_DATE: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.CLOSE_DATE.V1',
  FIELD_OWNER: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.OWNER.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.CRM.PIPELINE.EVENT.OPPORTUNITY.V1.CREATED.V1',
  EVENT_UPDATED: 'HERA.CRM.PIPELINE.EVENT.OPPORTUNITY.V1.UPDATED.V1',
  EVENT_DELETED: 'HERA.CRM.PIPELINE.EVENT.OPPORTUNITY.V1.DELETED.V1',
  EVENT_STATUS_CHANGED: 'HERA.CRM.PIPELINE.EVENT.OPPORTUNITY.V1.STATUS_CHANGED.V1'
} as const

/**
 * Opportunities Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function OpportunitiesPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedOpportunities, setSelectedOpportunities] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentOpportunity, setCurrentOpportunity] = useState<Opportunity | null>(null)
  const [opportunityToDelete, setOpportunityToDelete] = useState<Opportunity | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    workflow_stage: '',
    approval_status: '',
    // Dynamic filter fields
    account: '',
    contact: '',
    value: ''
  })

  // HERA Universal Entity Integration
  const opportunityData = useUniversalEntity({
    entity_type: 'OPPORTUNITY',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: true,
      status: 'active'
    },
    dynamicFields: [
      { name: 'account', type: 'text', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.ACCOUNT.V1', required: true },
      { name: 'contact', type: 'text', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.CONTACT.V1', required: false },
      { name: 'value', type: 'number', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.VALUE.V1', required: false },
      { name: 'stage', type: 'text', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.STAGE.V1', required: false },
      { name: 'probability', type: 'number', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.PROBABILITY.V1', required: false },
      { name: 'close_date', type: 'date', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.CLOSE_DATE.V1', required: false },
      { name: 'owner', type: 'text', smart_code: 'HERA.CRM.PIPELINE.DYN.OPPORTUNITY.V1.OWNER.V1', required: true }
    ]
  })

  // Transform entities with business rule extensions
  const opportunitys: Opportunity[] = opportunityData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      account: entity.dynamic_data?.find((d: any) => d.field_name === 'account')?.field_value_text || '',
      contact: entity.dynamic_data?.find((d: any) => d.field_name === 'contact')?.field_value_text || '',
      value: entity.dynamic_data?.find((d: any) => d.field_name === 'value')?.field_value_number || 0,
      stage: entity.dynamic_data?.find((d: any) => d.field_name === 'stage')?.field_value_text || '',
      probability: entity.dynamic_data?.find((d: any) => d.field_name === 'probability')?.field_value_number || 0,
      close_date: entity.dynamic_data?.find((d: any) => d.field_name === 'close_date')?.field_value_text || '',
      owner: entity.dynamic_data?.find((d: any) => d.field_name === 'owner')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      ,
      // Approval status from relationships
      approval_status: entity.relationships?.find((r: any) => r.relationship_type === 'APPROVAL_STATUS')?.target_entity?.entity_name?.toLowerCase() as any || 'pending',
      // Workflow stage from relationships
      workflow_stage: entity.relationships?.find((r: any) => r.relationship_type === 'WORKFLOW_STAGE')?.target_entity?.entity_name || 'new'
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total Opportunities',
      value: opportunitys.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: TrendingUp
    },
    {
      title: 'Active Opportunities',
      value: opportunitys.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: opportunitys.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    },
    {
      title: 'Pending Approval',
      value: opportunitys.filter(item => item.approval_status === 'pending').length.toString(),
      change: '-1.2%',
      trend: 'down' as const,
      icon: Clock
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'Opportunity Name', sortable: true },
    { key: 'account', label: 'Account', sortable: true },
    { key: 'contact', label: 'Contact', sortable: true },
    { key: 'value', label: 'Value', sortable: true },
    { key: 'stage', label: 'Stage', sortable: true },
    { key: 'probability', label: 'Probability', sortable: true },
    { key: 'workflow_stage', label: 'Stage', sortable: true },
    { key: 'approval_status', label: 'Approval', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search Opportunities', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'workflow_stage', label: 'Workflow Stage', type: 'select', options: [
      { value: '', label: 'All Stages' },
      { value: 'new', label: 'New' },
      { value: 'in_progress', label: 'In Progress' },
      { value: 'completed', label: 'Completed' }
    ]},
    { key: 'approval_status', label: 'Approval Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'pending', label: 'Pending' },
      { value: 'approved', label: 'Approved' },
      { value: 'rejected', label: 'Rejected' }
    ]},
    { key: 'account', label: 'Account', type: 'select', options: [
        { value: '', label: 'All Accounts' },
        ...Array.from(new Set(opportunitys.map(item => item.account).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'contact', label: 'Contact', type: 'select', options: [
        { value: '', label: 'All Contacts' },
        ...Array.from(new Set(opportunitys.map(item => item.contact).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddOpportunity = async (opportunityData: any) => {
    try {
      const result = await opportunityData.create({
        entity_type: 'OPPORTUNITY',
        entity_name: opportunityData.entity_name,
        smart_code: OPPORTUNITY_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, opportunityData)

      // Emit creation event for audit trail
      await opportunityData.emitEvent(OPPORTUNITY_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: opportunityData
      })

      setShowAddModal(false)
      console.log('✅ Opportunity created successfully')
    } catch (error) {
      console.error('❌ Error adding opportunity:', error)
    }
  }

  const handleEditOpportunity = async (opportunityData: any) => {
    if (!currentOpportunity) return
    
    try {
      await opportunityData.update(currentOpportunity.entity_id!, {
        entity_name: opportunityData.entity_name
      }, opportunityData)

      // Emit update event
      await opportunityData.emitEvent(OPPORTUNITY_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentOpportunity.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: opportunityData
      })

      setShowEditModal(false)
      setCurrentOpportunity(null)
      console.log('✅ Opportunity updated successfully')
    } catch (error) {
      console.error('❌ Error updating opportunity:', error)
    }
  }

  const handleDeleteOpportunity = async () => {
    if (!opportunityToDelete) return
    
    try {
      await opportunityData.delete(opportunityToDelete.entity_id!)

      // Emit deletion event
      await opportunityData.emitEvent(OPPORTUNITY_SMART_CODES.EVENT_DELETED, {
        entity_id: opportunityToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: opportunityToDelete.entity_name
      })

      setShowDeleteModal(false)
      setOpportunityToDelete(null)
      console.log('✅ Opportunity deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting opportunity:', error)
    }
  }

  
  const handleWorkflowChange = async (entityId: string, newStage: string) => {
    try {
      await opportunityData.emitEvent(OPPORTUNITY_SMART_CODES.EVENT_STATUS_CHANGED, {
        entity_id: entityId,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        old_stage: 'previous_stage', // Would get from current state
        new_stage: newStage
      })
      console.log('✅ Workflow stage changed successfully')
    } catch (error) {
      console.error('❌ Error changing workflow stage:', error)
    }
  }
  
  const handleApproval = async (entityId: string, approved: boolean) => {
    try {
      const approvalStatus = approved ? 'approved' : 'rejected'
      
      // Create approval relationship
      await opportunityData.createRelationship({
        source_entity_id: entityId,
        target_entity_id: 'approval_status_entity_id', // Would be looked up
        relationship_type: 'APPROVAL_STATUS',
        organization_id: currentOrganization?.id
      })
      
      console.log(`✅ Opportunity ${approvalStatus} successfully`)
    } catch (error) {
      console.error('❌ Error processing approval:', error)
    }
  }

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access Opportunities.</p>
      </div>
    )
  }

  if (opportunityData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading Opportunities...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="Opportunities"
      subtitle={`${opportunitys.length} total opportunitys`}
      primaryColor="#6264a7"
      accentColor="#464775"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#6264a7' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={opportunitys}
        columns={columns}
        selectedRows={selectedOpportunities}
        onRowSelect={setSelectedOpportunities}
        onRowClick={(opportunity) => {
          setCurrentOpportunity(opportunity)
          setShowEditModal(true)
        }}
        showBulkActions={selectedOpportunities.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedOpportunities) {
                await opportunityData.delete(id.toString())
              }
              setSelectedOpportunities([])
            },
            variant: 'destructive'
          },
          {
            label: 'Bulk Approve',
            action: async () => {
              // Implement bulk approval
            },
            variant: 'default'
          }
        ]}
        mobileCardRender={(opportunity) => (
          <MobileCard key={opportunity.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{opportunity.entity_name}</h3>
                <p className="text-sm text-gray-500">Stage: {opportunity.workflow_stage}</p>
                <div className="flex items-center mt-1">
                  {opportunity.approval_status === 'approved' ? <CheckCircle className="h-4 w-4 text-green-500 mr-1" /> : 
                   opportunity.approval_status === 'pending' ? <Clock className="h-4 w-4 text-yellow-500 mr-1" /> : 
                   <AlertCircle className="h-4 w-4 text-red-500 mr-1" />}
                  <span className="text-sm capitalize">{opportunity.approval_status}</span>
                </div>
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentOpportunity(opportunity)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setOpportunityToDelete(opportunity)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Account:</span>{' '}
              {opportunity.account || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Contact:</span>{' '}
              {opportunity.contact || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Value:</span>{' '}
              {opportunity.value || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Stage:</span>{' '}
              {opportunity.stage || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {opportunity.created_at ? new Date(opportunity.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#6264a7' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <OpportunityModal
          title="Add New Opportunity"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddOpportunity}
          dynamicFields={opportunityData.dynamicFieldsConfig || []}
          businessRules={{"status_workflow":true,"requires_approval":true,"audit_trail":true}}
        />
      )}

      {showEditModal && currentOpportunity && (
        <OpportunityModal
          title="Edit Opportunity"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentOpportunity(null)
          }}
          onSave={handleEditOpportunity}
          initialData={currentOpportunity}
          dynamicFields={opportunityData.dynamicFieldsConfig || []}
          businessRules={{"status_workflow":true,"requires_approval":true,"audit_trail":true}}
        />
      )}

      {showDeleteModal && opportunityToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete Opportunity</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{opportunityToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setOpportunityToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteOpportunity}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise Opportunity Modal Component
 * Enhanced with business rules and validation
 */
interface OpportunityModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: Opportunity
  dynamicFields: any[]
  businessRules: any
}

function OpportunityModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: OpportunityModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof Opportunity] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'Opportunity name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Opportunity Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Account *
              </label>
              <input
                type="text"
                value={formData.account}
                onChange={(e) => setFormData({ ...formData, account: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.account ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.account && (
                <p className="mt-1 text-sm text-red-600">{errors.account}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Contact 
              </label>
              <input
                type="text"
                value={formData.contact}
                onChange={(e) => setFormData({ ...formData, contact: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.contact ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.contact && (
                <p className="mt-1 text-sm text-red-600">{errors.contact}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Value 
              </label>
              <input
                type="number"
                value={formData.value}
                onChange={(e) => setFormData({ ...formData, value: parseFloat(e.target.value) || 0 })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.value ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.value && (
                <p className="mt-1 text-sm text-red-600">{errors.value}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Stage 
              </label>
              <input
                type="text"
                value={formData.stage}
                onChange={(e) => setFormData({ ...formData, stage: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.stage ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.stage && (
                <p className="mt-1 text-sm text-red-600">{errors.stage}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Probability 
              </label>
              <input
                type="number"
                value={formData.probability}
                onChange={(e) => setFormData({ ...formData, probability: parseFloat(e.target.value) || 0 })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.probability ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.probability && (
                <p className="mt-1 text-sm text-red-600">{errors.probability}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Close Date 
              </label>
              <input
                type="date"
                value={formData.close_date}
                onChange={(e) => setFormData({ ...formData, close_date: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.close_date ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.close_date && (
                <p className="mt-1 text-sm text-red-600">{errors.close_date}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Owner *
              </label>
              <input
                type="text"
                value={formData.owner}
                onChange={(e) => setFormData({ ...formData, owner: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.owner ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.owner && (
                <p className="mt-1 text-sm text-red-600">{errors.owner}</p>
              )}
            </div>

            {/* Business Rules Info */}
            
            <div className="bg-yellow-50 border border-yellow-200 rounded-md p-3">
              <div className="flex items-center">
                <Clock className="h-4 w-4 text-yellow-600 mr-2" />
                <p className="text-sm text-yellow-800">
                  This opportunity will require approval before becoming active.
                </p>
              </div>
            </div>

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#6264a7' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}