# Finance Manager Role Policy
role: FINANCE_MANAGER
allow:
  - api: "POST /api/v1/fiscal/closing-step"
    smart_code_family: "HERA.FISCAL.**"
  - api: "GET /api/v1/reports/**"
    smart_code_family: "HERA.FIN.REPORT.**"
  - api: "GET /api/v1/audit/**"
    smart_code_family: "HERA.SECURITY.AUDIT.**"
  - smart_code_family: "HERA.ACCOUNTING.**"
    actions: ["read", "write", "approve"]
  - smart_code_family: "HERA.FIN.GL.**"
    actions: ["read", "write"]
  - smart_code_family: "HERA.FIN.BUDGET.**"
    actions: ["read", "write", "approve"]
deny:
  - api: "DELETE /api/v1/**"
  - smart_code_family: "HERA.SECURITY.ADMIN.**"
  - smart_code_family: "HERA.SYSTEM.**"
conditions:
  - type: time_based
    config:
      business_hours_only: true
      allowed_hours: [7, 19]  # 7 AM to 7 PM
  - type: mfa_required
    config:
      for_sensitive_operations: true