'use client'

/**
 * Staff CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: WASTE_MANAGEMENT
 * Entity: STAFF
 * Smart Code: HERA.WASTE.MASTER.ENTITY.STAFF.v1
 * Description: Drivers, helpers, supervisors, inspectors
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  UserCheck,
  X
} from 'lucide-react'

/**
 * Staff Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface Staff extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  first_name?: string
  last_name?: string
  role?: string
  license_no?: string
  hourly_rate?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA Staff Smart Codes
 * Auto-generated from preset configuration
 */
const STAFF_SMART_CODES = {
  ENTITY: 'HERA.WASTE.MASTER.ENTITY.STAFF.v1',
  FIELD_FIRST_NAME: 'HERA.WASTE.MASTER.DYN.STAFF.v1.FIRST_NAME.V1',
  FIELD_LAST_NAME: 'HERA.WASTE.MASTER.DYN.STAFF.v1.LAST_NAME.V1',
  FIELD_ROLE: 'HERA.WASTE.MASTER.DYN.STAFF.v1.ROLE.V1',
  FIELD_LICENSE_NO: 'HERA.WASTE.MASTER.DYN.STAFF.v1.LICENSE_NO.V1',
  FIELD_HOURLY_RATE: 'HERA.WASTE.MASTER.DYN.STAFF.v1.HOURLY_RATE.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.WASTE.MASTER.EVENT.STAFF.v1.CREATED.V1',
  EVENT_UPDATED: 'HERA.WASTE.MASTER.EVENT.STAFF.v1.UPDATED.V1',
  EVENT_DELETED: 'HERA.WASTE.MASTER.EVENT.STAFF.v1.DELETED.V1'
} as const

/**
 * Staff Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function StaffPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedStaff, setSelectedStaff] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentStaff, setCurrentStaff] = useState<Staff | null>(null)
  const [staffToDelete, setStaffToDelete] = useState<Staff | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    first_name: '',
    last_name: '',
    role: ''
  })

  // HERA Universal Entity Integration
  const staffData = useUniversalEntity({
    entity_type: 'STAFF',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'first_name', type: 'text', smart_code: 'HERA.WASTE.MASTER.DYN.STAFF.v1.FIRST_NAME.V1', required: false },
      { name: 'last_name', type: 'text', smart_code: 'HERA.WASTE.MASTER.DYN.STAFF.v1.LAST_NAME.V1', required: false },
      { name: 'role', type: 'text', smart_code: 'HERA.WASTE.MASTER.DYN.STAFF.v1.ROLE.V1', required: false },
      { name: 'license_no', type: 'text', smart_code: 'HERA.WASTE.MASTER.DYN.STAFF.v1.LICENSE_NO.V1', required: false },
      { name: 'hourly_rate', type: 'text', smart_code: 'HERA.WASTE.MASTER.DYN.STAFF.v1.HOURLY_RATE.V1', required: false }
    ]
  })

  // Transform entities with business rule extensions
  const staffs: Staff[] = staffData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      first_name: entity.dynamic_data?.find((d: any) => d.field_name === 'first_name')?.field_value_text || '',
      last_name: entity.dynamic_data?.find((d: any) => d.field_name === 'last_name')?.field_value_text || '',
      role: entity.dynamic_data?.find((d: any) => d.field_name === 'role')?.field_value_text || '',
      license_no: entity.dynamic_data?.find((d: any) => d.field_name === 'license_no')?.field_value_text || '',
      hourly_rate: entity.dynamic_data?.find((d: any) => d.field_name === 'hourly_rate')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total Staff',
      value: staffs.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: UserCheck
    },
    {
      title: 'Active Staff',
      value: staffs.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: staffs.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'Staff Name', sortable: true },
    { key: 'first_name', label: 'First name', sortable: true },
    { key: 'last_name', label: 'Last name', sortable: true },
    { key: 'role', label: 'Role', sortable: true },
    { key: 'license_no', label: 'License no', sortable: true },
    { key: 'hourly_rate', label: 'Hourly rate', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search Staff', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'first_name', label: 'First Name', type: 'select', options: [
        { value: '', label: 'All First Names' },
        ...Array.from(new Set(staffs.map(item => item.first_name).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'last_name', label: 'Last Name', type: 'select', options: [
        { value: '', label: 'All Last Names' },
        ...Array.from(new Set(staffs.map(item => item.last_name).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddStaff = async (staffData: any) => {
    try {
      const result = await staffData.create({
        entity_type: 'STAFF',
        entity_name: staffData.entity_name,
        smart_code: STAFF_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, staffData)

      // Emit creation event for audit trail
      await staffData.emitEvent(STAFF_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: staffData
      })

      setShowAddModal(false)
      console.log('✅ Staff created successfully')
    } catch (error) {
      console.error('❌ Error adding staff:', error)
    }
  }

  const handleEditStaff = async (staffData: any) => {
    if (!currentStaff) return
    
    try {
      await staffData.update(currentStaff.entity_id!, {
        entity_name: staffData.entity_name
      }, staffData)

      // Emit update event
      await staffData.emitEvent(STAFF_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentStaff.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: staffData
      })

      setShowEditModal(false)
      setCurrentStaff(null)
      console.log('✅ Staff updated successfully')
    } catch (error) {
      console.error('❌ Error updating staff:', error)
    }
  }

  const handleDeleteStaff = async () => {
    if (!staffToDelete) return
    
    try {
      await staffData.delete(staffToDelete.entity_id!)

      // Emit deletion event
      await staffData.emitEvent(STAFF_SMART_CODES.EVENT_DELETED, {
        entity_id: staffToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: staffToDelete.entity_name
      })

      setShowDeleteModal(false)
      setStaffToDelete(null)
      console.log('✅ Staff deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting staff:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access Staff.</p>
      </div>
    )
  }

  if (staffData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading Staff...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="Staff"
      subtitle={`${staffs.length} total staffs`}
      primaryColor="#059669"
      accentColor="#047857"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#059669' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={staffs}
        columns={columns}
        selectedRows={selectedStaff}
        onRowSelect={setSelectedStaff}
        onRowClick={(staff) => {
          setCurrentStaff(staff)
          setShowEditModal(true)
        }}
        showBulkActions={selectedStaff.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedStaff) {
                await staffData.delete(id.toString())
              }
              setSelectedStaff([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(staff) => (
          <MobileCard key={staff.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{staff.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentStaff(staff)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setStaffToDelete(staff)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">First Name:</span>{' '}
              {staff.first_name || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Last Name:</span>{' '}
              {staff.last_name || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Role:</span>{' '}
              {staff.role || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">License No:</span>{' '}
              {staff.license_no || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {staff.created_at ? new Date(staff.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#059669' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <StaffModal
          title="Add New Staff"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddStaff}
          dynamicFields={staffData.dynamicFieldsConfig || []}
          businessRules={{"license_validation":true,"audit_trail":true}}
        />
      )}

      {showEditModal && currentStaff && (
        <StaffModal
          title="Edit Staff"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentStaff(null)
          }}
          onSave={handleEditStaff}
          initialData={currentStaff}
          dynamicFields={staffData.dynamicFieldsConfig || []}
          businessRules={{"license_validation":true,"audit_trail":true}}
        />
      )}

      {showDeleteModal && staffToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete Staff</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{staffToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setStaffToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteStaff}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise Staff Modal Component
 * Enhanced with business rules and validation
 */
interface StaffModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: Staff
  dynamicFields: any[]
  businessRules: any
}

function StaffModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: StaffModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof Staff] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'Staff name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Staff Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                First Name 
              </label>
              <input
                type="text"
                value={formData.first_name}
                onChange={(e) => setFormData({ ...formData, first_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.first_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.first_name && (
                <p className="mt-1 text-sm text-red-600">{errors.first_name}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Last Name 
              </label>
              <input
                type="text"
                value={formData.last_name}
                onChange={(e) => setFormData({ ...formData, last_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.last_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.last_name && (
                <p className="mt-1 text-sm text-red-600">{errors.last_name}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Role 
              </label>
              <input
                type="text"
                value={formData.role}
                onChange={(e) => setFormData({ ...formData, role: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.role ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.role && (
                <p className="mt-1 text-sm text-red-600">{errors.role}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                License No 
              </label>
              <input
                type="text"
                value={formData.license_no}
                onChange={(e) => setFormData({ ...formData, license_no: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.license_no ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.license_no && (
                <p className="mt-1 text-sm text-red-600">{errors.license_no}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Hourly Rate 
              </label>
              <input
                type="text"
                value={formData.hourly_rate}
                onChange={(e) => setFormData({ ...formData, hourly_rate: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.hourly_rate ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.hourly_rate && (
                <p className="mt-1 text-sm text-red-600">{errors.hourly_rate}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#059669' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}