/**
 * HERA DNA SDK Examples
 * Smart code examples for reference
 */

export const SMART_CODE_EXAMPLES = {
  // CRM Module
  CRM: {
    CUSTOMER_CREATE: 'HERA.CRM.CUST.ENT.PROF.v1',
    LEAD_CREATE: 'HERA.CRM.LEAD.ENT.PROSPECT.v1',
    SALE_ORDER: 'HERA.CRM.SALE.TXN.ORDER.v1',
    CUSTOMER_DYNAMIC_CREDIT: 'HERA.CRM.CUST.DYN.CREDIT.v1',
    CUSTOMER_DYNAMIC_TERMS: 'HERA.CRM.CUST.DYN.TERMS.v1'
  },
  
  // Finance Module
  FIN: {
    GL_ACCOUNT_ASSET: 'HERA.FIN.GL.ACC.ASSET.v1',
    GL_ACCOUNT_LIABILITY: 'HERA.FIN.GL.ACC.LIABILITY.v1',
    JOURNAL_ENTRY: 'HERA.FIN.GL.TXN.JOURNAL.v1',
    INVOICE_CREATE: 'HERA.FIN.AR.TXN.INVOICE.v1',
    PAYMENT_RECEIVE: 'HERA.FIN.AR.TXN.RCP.v1'
  },
  
  // HR Module
  HR: {
    EMPLOYEE_CREATE: 'HERA.HR.EMP.ENT.STAFF.v1',
    PAYROLL_RUN: 'HERA.HR.PAYROLL.TXN.RUN.v1',
    LEAVE_REQUEST: 'HERA.HR.LEAVE.TXN.REQUEST.v1',
    EMPLOYEE_DYNAMIC_SALARY: 'HERA.HR.EMP.DYN.SALARY.v1'
  },
  
  // WhatsApp Module
  WHATSAPP: {
    THREAD_CREATE: 'HERA.WHATSAPP.INBOX.THREAD.v1',
    MESSAGE_TEXT: 'HERA.WHATSAPP.MESSAGE.TEXT.v1',
    MESSAGE_MEDIA: 'HERA.WHATSAPP.MESSAGE.MEDIA.v1',
    TEMPLATE_REGISTER: 'HERA.WHATSAPP.TEMPLATE.REGISTER.v1',
    CAMPAIGN_CREATE: 'HERA.WHATSAPP.CAMPAIGN.OUTBOUND.v1'
  },
  
  // Workflow Module
  WORKFLOW: {
    STATUS_ASSIGN: 'HERA.WORKFLOW.STATUS.ASSIGN.v1',
    STATUS_DRAFT: 'HERA.WORKFLOW.STATUS.DRAFT.v1',
    STATUS_PENDING: 'HERA.WORKFLOW.STATUS.PENDING.v1',
    STATUS_APPROVED: 'HERA.WORKFLOW.STATUS.APPROVED.v1',
    STATUS_REJECTED: 'HERA.WORKFLOW.STATUS.REJECTED.v1'
  }
} as const;

// Export type for example categories
export type SmartCodeExampleCategory = keyof typeof SMART_CODE_EXAMPLES;