/**
 * Cashew Materials Management Page
 * 
 * Generated by HERA Frontend Generator
 * Uses HERAMasterDataTemplate for consistent enterprise UX
 */

'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import HERAMasterDataTemplate from '@/components/hera/HERAMasterDataTemplate'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { 
  Search, 
  Plus, 
  Package,
  Building2,
  MapPin,
  DollarSign,
  FileText
} from 'lucide-react'

// Material-specific form configuration using HERAMasterDataTemplate patterns
const MATERIAL_SECTIONS = [
  {
    id: 'basic',
    label: 'Basic Information',
    icon: Package,
    required: true,
    description: 'Enter basic material information and categorization'
  },
  {
    id: 'sourcing',
    label: 'Sourcing Details',
    icon: Building2,
    required: false,
    description: 'Supplier and sourcing information'
  },
  {
    id: 'storage',
    label: 'Storage & Handling',
    icon: MapPin,
    required: false,
    description: 'Storage requirements and handling instructions'
  }
]

const MATERIAL_FIELDS = [
  {
    id: 'entity_name',
    label: 'Material Name',
    type: 'text' as const,
    required: true,
    placeholder: 'Enter material name',
    section: 'basic',
    validation: (value: string) => {
      return !value.trim() ? 'Material name is required' : null
    }
  },
  {
    id: 'entity_code',
    label: 'Material Code',
    type: 'text' as const,
    required: true,
    placeholder: 'Auto-generated from name',
    section: 'basic'
  },
  {
    id: 'category',
    label: 'Material Category',
    type: 'select' as const,
    required: true,
    section: 'basic',
    options: [
      { value: 'raw_cashew', label: 'Raw Cashews', description: 'Unprocessed cashew nuts' },
      { value: 'packaging', label: 'Packaging Materials', description: 'Boxes, bags, labels' },
      { value: 'consumables', label: 'Consumables', description: 'Processing aids and consumables' },
      { value: 'chemicals', label: 'Processing Chemicals', description: 'Salt, preservatives, etc.' }
    ]
  },
  {
    id: 'description',
    label: 'Description',
    type: 'textarea' as const,
    placeholder: 'Detailed material description',
    section: 'basic'
  },
  {
    id: 'supplier_name',
    label: 'Primary Supplier',
    type: 'text' as const,
    placeholder: 'Main supplier name',
    section: 'sourcing'
  },
  {
    id: 'origin_country',
    label: 'Country of Origin',
    type: 'text' as const,
    placeholder: 'Country where material originates',
    section: 'sourcing'
  },
  {
    id: 'storage_conditions',
    label: 'Storage Conditions',
    type: 'select' as const,
    section: 'storage',
    options: [
      { value: 'ambient', label: 'Ambient Temperature', description: 'Normal room temperature storage' },
      { value: 'cool_dry', label: 'Cool & Dry', description: 'Controlled humidity environment' },
      { value: 'refrigerated', label: 'Refrigerated', description: 'Cold storage required' },
      { value: 'controlled', label: 'Controlled Environment', description: 'Specific temperature and humidity' }
    ]
  },
  {
    id: 'shelf_life_days',
    label: 'Shelf Life (Days)',
    type: 'number' as const,
    placeholder: 'Shelf life in days',
    section: 'storage'
  }
]

export default function CashewMaterialsPage() {
  const router = useRouter()
  const { user, organization, isAuthenticated, isLoading } = useHERAAuth()
  const [showCreateForm, setShowCreateForm] = useState(false)

  // Authentication checks using HERA Universal Auth
  if (isLoading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <div className="animate-spin h-8 w-8 border-4 border-primary border-t-transparent rounded-full"></div>
      </div>
    )
  }

  if (!isAuthenticated) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Alert>
          <AlertDescription>Please log in to access materials management.</AlertDescription>
        </Alert>
      </div>
    )
  }

  if (!organization?.id) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Alert>
          <AlertDescription>No organization context available.</AlertDescription>
        </Alert>
      </div>
    )
  }

  // Handle create form submission using HERA Universal API
  const handleCreateMaterial = async (formData: Record<string, any>) => {
    try {
      console.log('Creating material with HERA Universal Auth:', {
        formData,
        organization: organization?.id,
        user: user?.entity_id,
        hasToken: !!accessToken
      })
      
      // Create entity using HERA API v2 with proper authentication
      const response = await fetch('/api/v2/entities', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${accessToken}`,
          'X-Organization-Id': organization!.id
        },
        body: JSON.stringify({
          operation: 'create',
          entity_type: 'MATERIAL',
          smart_code: 'HERA.CASHEW.MATERIAL.ENTITY.v1',
          organization_id: organization!.id,
          entity_data: {
            entity_name: formData.entity_name,
            entity_code: formData.entity_code || formData.entity_name.toUpperCase().replace(/\s+/g, '_'),
            entity_type: 'MATERIAL'
          },
          dynamic_fields: [
            {
              field_name: 'category',
              field_value: formData.category,
              field_type: 'text',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.CATEGORY.v1'
            },
            {
              field_name: 'description',
              field_value: formData.description || '',
              field_type: 'text',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.DESCRIPTION.v1'
            },
            {
              field_name: 'supplier_name',
              field_value: formData.supplier_name || '',
              field_type: 'text',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.SUPPLIER.v1'
            },
            {
              field_name: 'origin_country',
              field_value: formData.origin_country || '',
              field_type: 'text',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.ORIGIN.v1'
            },
            {
              field_name: 'storage_conditions',
              field_value: formData.storage_conditions || 'ambient',
              field_type: 'text',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.STORAGE.v1'
            },
            {
              field_name: 'shelf_life_days',
              field_value: formData.shelf_life_days || 0,
              field_type: 'number',
              smart_code: 'HERA.CASHEW.MATERIAL.FIELD.SHELF_LIFE.v1'
            }
          ]
        })
      })
      
      if (!response.ok) {
        throw new Error(`API Error: ${response.status} ${response.statusText}`)
      }
      
      const result = await response.json()
      console.log('Material created successfully:', result)
      
      // Close form and refresh
      setShowCreateForm(false)
      router.refresh()
      
    } catch (error) {
      console.error('Failed to create material:', error)
      // In a real app, show error toast or alert
      alert('Failed to create material. Please try again.')
    }
  }

  // Show create form using HERAMasterDataTemplate
  if (showCreateForm) {
    return (
      <HERAMasterDataTemplate
        entityType="material"
        entityLabel="Material"
        sections={MATERIAL_SECTIONS}
        fields={MATERIAL_FIELDS}
        backUrl="/cashew/materials"
        onSubmit={handleCreateMaterial}
      />
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 p-6">
      {/* Mobile header - following HERA mobile-first standards */}
      <div className="h-11 bg-gradient-to-b from-black/20 to-transparent md:hidden" />
      
      <div className="md:hidden sticky top-0 z-50 bg-white border-b border-gray-200">
        <div className="flex items-center justify-between p-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-100 flex items-center justify-center">
              <Package className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h1 className="text-lg font-bold text-gray-900">Materials</h1>
              <p className="text-xs text-gray-600">HERA Cashew Manufacturing</p>
            </div>
          </div>
          <button 
            onClick={() => setShowCreateForm(true)}
            className="min-w-[44px] min-h-[44px] rounded-full bg-blue-100 flex items-center justify-center active:scale-95"
          >
            <Plus className="w-5 h-5 text-blue-600" />
          </button>
        </div>
      </div>

      {/* Desktop header */}
      <div className="hidden md:block mb-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">Materials Management</h1>
            <p className="text-gray-600">Manage raw cashews, packaging, and consumables</p>
          </div>
          <div className="flex items-center gap-3">
            <Button
              onClick={() => setShowCreateForm(true)}
              className="flex items-center gap-2"
            >
              <Plus className="w-4 h-4" />
              New Material
            </Button>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="text-center py-12">
        <div className="w-16 h-16 rounded-xl bg-gray-100 flex items-center justify-center mx-auto mb-4">
          <Package className="w-8 h-8 text-gray-400" />
        </div>
        <div className="text-gray-500 mb-4">Materials management ready</div>
        <p className="text-gray-400 mb-6">Click "New Material" to add raw cashews, packaging materials, or consumables</p>
        <Button onClick={() => setShowCreateForm(true)}>
          <Plus className="w-4 h-4 mr-2" />
          Add Your First Material
        </Button>
      </div>

      {/* Mobile bottom spacing */}
      <div className="h-24 md:h-0" />
    </div>
  )
}