'use client'

/**
 * Customers CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: CRM
 * Entity: CUSTOMER
 * Smart Code: HERA.CRM.CORE.ENTITY.CUSTOMER.v1
 * Description: Customer master data for any business domain
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  Users,
  X
} from 'lucide-react'

/**
 * Customer Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface Customer extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  industry?: string
  website?: string
  employees?: number
  revenue?: number
  owner?: string
  phone?: string
  email?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA Customer Smart Codes
 * Auto-generated from preset configuration
 */
const CUSTOMER_SMART_CODES = {
  ENTITY: 'HERA.CRM.CORE.ENTITY.CUSTOMER.v1',
  FIELD_INDUSTRY: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.INDUSTRY.v1',
  FIELD_WEBSITE: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.WEBSITE.v1',
  FIELD_EMPLOYEES: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.EMPLOYEES.v1',
  FIELD_REVENUE: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.REVENUE.v1',
  FIELD_OWNER: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.OWNER.v1',
  FIELD_PHONE: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.PHONE.v1',
  FIELD_EMAIL: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.EMAIL.v1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.CRM.CORE.EVENT.CUSTOMER.v1.CREATED.v1',
  EVENT_UPDATED: 'HERA.CRM.CORE.EVENT.CUSTOMER.v1.UPDATED.v1',
  EVENT_DELETED: 'HERA.CRM.CORE.EVENT.CUSTOMER.v1.DELETED.v1'
} as const

/**
 * Customers Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function CustomersPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedCustomers, setSelectedCustomers] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentCustomer, setCurrentCustomer] = useState<Customer | null>(null)
  const [customerToDelete, setCustomerToDelete] = useState<Customer | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    industry: '',
    website: '',
    employees: ''
  })

  // HERA Universal Entity Integration
  const customerData = useUniversalEntity({
    entity_type: 'CUSTOMER',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'industry', type: 'text', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.INDUSTRY.v1', required: true },
      { name: 'website', type: 'url', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.WEBSITE.v1', required: false },
      { name: 'employees', type: 'number', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.EMPLOYEES.v1', required: false },
      { name: 'revenue', type: 'number', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.REVENUE.v1', required: false },
      { name: 'owner', type: 'text', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.OWNER.v1', required: true },
      { name: 'phone', type: 'phone', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.PHONE.v1', required: true },
      { name: 'email', type: 'email', smart_code: 'HERA.CRM.CORE.DYN.CUSTOMER.v1.EMAIL.v1', required: true }
    ]
  })

  // Transform entities with business rule extensions
  const customers: Customer[] = customerData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      industry: entity.dynamic_data?.find((d: any) => d.field_name === 'industry')?.field_value_text || '',
      website: entity.dynamic_data?.find((d: any) => d.field_name === 'website')?.field_value_text || '',
      employees: entity.dynamic_data?.find((d: any) => d.field_name === 'employees')?.field_value_number || 0,
      revenue: entity.dynamic_data?.find((d: any) => d.field_name === 'revenue')?.field_value_number || 0,
      owner: entity.dynamic_data?.find((d: any) => d.field_name === 'owner')?.field_value_text || '',
      phone: entity.dynamic_data?.find((d: any) => d.field_name === 'phone')?.field_value_text || '',
      email: entity.dynamic_data?.find((d: any) => d.field_name === 'email')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total Customers',
      value: customers.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: Users
    },
    {
      title: 'Active Customers',
      value: customers.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: customers.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'Customer Name', sortable: true },
    { key: 'industry', label: 'Industry', sortable: true },
    { key: 'website', label: 'Website', sortable: true },
    { key: 'employees', label: 'Employees', sortable: true },
    { key: 'revenue', label: 'Revenue', sortable: true },
    { key: 'owner', label: 'Owner', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search Customers', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'industry', label: 'Industry', type: 'select', options: [
        { value: '', label: 'All Industrys' },
        ...Array.from(new Set(customers.map(item => item.industry).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddCustomer = async (customerData: any) => {
    try {
      const result = await customerData.create({
        entity_type: 'CUSTOMER',
        entity_name: customerData.entity_name,
        smart_code: CUSTOMER_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, customerData)

      // Emit creation event for audit trail
      await customerData.emitEvent(CUSTOMER_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: customerData
      })

      setShowAddModal(false)
      console.log('✅ Customer created successfully')
    } catch (error) {
      console.error('❌ Error adding customer:', error)
    }
  }

  const handleEditCustomer = async (customerData: any) => {
    if (!currentCustomer) return
    
    try {
      await customerData.update(currentCustomer.entity_id!, {
        entity_name: customerData.entity_name
      }, customerData)

      // Emit update event
      await customerData.emitEvent(CUSTOMER_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentCustomer.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: customerData
      })

      setShowEditModal(false)
      setCurrentCustomer(null)
      console.log('✅ Customer updated successfully')
    } catch (error) {
      console.error('❌ Error updating customer:', error)
    }
  }

  const handleDeleteCustomer = async () => {
    if (!customerToDelete) return
    
    try {
      await customerData.delete(customerToDelete.entity_id!)

      // Emit deletion event
      await customerData.emitEvent(CUSTOMER_SMART_CODES.EVENT_DELETED, {
        entity_id: customerToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: customerToDelete.entity_name
      })

      setShowDeleteModal(false)
      setCustomerToDelete(null)
      console.log('✅ Customer deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting customer:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access Customers.</p>
      </div>
    )
  }

  if (customerData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading Customers...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="Customers"
      subtitle={`${customers.length} total customers`}
      primaryColor="#16a34a"
      accentColor="#15803d"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#16a34a' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={customers}
        columns={columns}
        selectedRows={selectedCustomers}
        onRowSelect={setSelectedCustomers}
        onRowClick={(customer) => {
          setCurrentCustomer(customer)
          setShowEditModal(true)
        }}
        showBulkActions={selectedCustomers.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedCustomers) {
                await customerData.delete(id.toString())
              }
              setSelectedCustomers([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(customer) => (
          <MobileCard key={customer.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{customer.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentCustomer(customer)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setCustomerToDelete(customer)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Industry:</span>{' '}
              {customer.industry || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Website:</span>{' '}
              {customer.website || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Employees:</span>{' '}
              {customer.employees || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Revenue:</span>{' '}
              {customer.revenue || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {customer.created_at ? new Date(customer.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#16a34a' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <CustomerModal
          title="Add New Customer"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddCustomer}
          dynamicFields={customerData.dynamicFieldsConfig || []}
          businessRules={{"duplicate_detection":true,"audit_trail":true,"geo_location_tracking":true}}
        />
      )}

      {showEditModal && currentCustomer && (
        <CustomerModal
          title="Edit Customer"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentCustomer(null)
          }}
          onSave={handleEditCustomer}
          initialData={currentCustomer}
          dynamicFields={customerData.dynamicFieldsConfig || []}
          businessRules={{"duplicate_detection":true,"audit_trail":true,"geo_location_tracking":true}}
        />
      )}

      {showDeleteModal && customerToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete Customer</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{customerToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setCustomerToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteCustomer}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise Customer Modal Component
 * Enhanced with business rules and validation
 */
interface CustomerModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: Customer
  dynamicFields: any[]
  businessRules: any
}

function CustomerModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: CustomerModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof Customer] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'Customer name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Customer Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Industry *
              </label>
              <input
                type="text"
                value={formData.industry}
                onChange={(e) => setFormData({ ...formData, industry: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.industry ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.industry && (
                <p className="mt-1 text-sm text-red-600">{errors.industry}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Website 
              </label>
              <input
                type="url"
                value={formData.website}
                onChange={(e) => setFormData({ ...formData, website: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.website ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.website && (
                <p className="mt-1 text-sm text-red-600">{errors.website}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Employees 
              </label>
              <input
                type="number"
                value={formData.employees}
                onChange={(e) => setFormData({ ...formData, employees: parseFloat(e.target.value) || 0 })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.employees ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.employees && (
                <p className="mt-1 text-sm text-red-600">{errors.employees}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Revenue 
              </label>
              <input
                type="number"
                value={formData.revenue}
                onChange={(e) => setFormData({ ...formData, revenue: parseFloat(e.target.value) || 0 })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.revenue ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.revenue && (
                <p className="mt-1 text-sm text-red-600">{errors.revenue}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Owner *
              </label>
              <input
                type="text"
                value={formData.owner}
                onChange={(e) => setFormData({ ...formData, owner: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.owner ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.owner && (
                <p className="mt-1 text-sm text-red-600">{errors.owner}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Phone *
              </label>
              <input
                type="tel"
                value={formData.phone}
                onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.phone ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.phone && (
                <p className="mt-1 text-sm text-red-600">{errors.phone}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Email *
              </label>
              <input
                type="email"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.email ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.email && (
                <p className="mt-1 text-sm text-red-600">{errors.email}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#16a34a' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}