[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"
restartPolicyMaxRetries = 3

[[services]]
name = "hera-mcp-server"
port = 3000
targetPort = 3000
protocol = "http"