'use client'

/**
 * GL Journals CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: FINANCE
 * Entity: GL_JOURNAL
 * Smart Code: HERA.FINANCE.TXN.ENTITY.GL_JOURNAL.v1
 * Description: General ledger journal entries for accounting
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  BookOpen,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  X
} from 'lucide-react'

/**
 * GLJournal Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface GLJournal extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  journal_number?: string
  description?: string
  journal_date?: string
  total_debit?: string
  total_credit?: string
  status?: string
  reference?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA GL Journal Smart Codes
 * Auto-generated from preset configuration
 */
const GL_JOURNAL_SMART_CODES = {
  ENTITY: 'HERA.FINANCE.TXN.ENTITY.GL_JOURNAL.v1',
  FIELD_JOURNAL_NUMBER: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.JOURNAL_NUMBER.V1',
  FIELD_DESCRIPTION: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.DESCRIPTION.V1',
  FIELD_JOURNAL_DATE: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.JOURNAL_DATE.V1',
  FIELD_TOTAL_DEBIT: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.TOTAL_DEBIT.V1',
  FIELD_TOTAL_CREDIT: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.TOTAL_CREDIT.V1',
  FIELD_STATUS: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.STATUS.V1',
  FIELD_REFERENCE: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.REFERENCE.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.FINANCE.TXN.EVENT.GL_JOURNAL.v1.CREATED.V1',
  EVENT_UPDATED: 'HERA.FINANCE.TXN.EVENT.GL_JOURNAL.v1.UPDATED.V1',
  EVENT_DELETED: 'HERA.FINANCE.TXN.EVENT.GL_JOURNAL.v1.DELETED.V1'
} as const

/**
 * GL Journals Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function GLJournalsPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedGLJournals, setSelectedGLJournals] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentGLJournal, setCurrentGLJournal] = useState<GLJournal | null>(null)
  const [gl_journalToDelete, setGLJournalToDelete] = useState<GLJournal | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    journal_number: '',
    description: '',
    journal_date: ''
  })

  // HERA Universal Entity Integration
  const gl_journalData = useUniversalEntity({
    entity_type: 'GL_JOURNAL',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'journal_number', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.JOURNAL_NUMBER.V1', required: false },
      { name: 'description', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.DESCRIPTION.V1', required: false },
      { name: 'journal_date', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.JOURNAL_DATE.V1', required: false },
      { name: 'total_debit', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.TOTAL_DEBIT.V1', required: false },
      { name: 'total_credit', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.TOTAL_CREDIT.V1', required: false },
      { name: 'status', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.STATUS.V1', required: false },
      { name: 'reference', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.GL_JOURNAL.v1.REFERENCE.V1', required: false }
    ]
  })

  // Transform entities with business rule extensions
  const gl_journals: GLJournal[] = gl_journalData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      journal_number: entity.dynamic_data?.find((d: any) => d.field_name === 'journal_number')?.field_value_text || '',
      description: entity.dynamic_data?.find((d: any) => d.field_name === 'description')?.field_value_text || '',
      journal_date: entity.dynamic_data?.find((d: any) => d.field_name === 'journal_date')?.field_value_text || '',
      total_debit: entity.dynamic_data?.find((d: any) => d.field_name === 'total_debit')?.field_value_text || '',
      total_credit: entity.dynamic_data?.find((d: any) => d.field_name === 'total_credit')?.field_value_text || '',
      status: entity.dynamic_data?.find((d: any) => d.field_name === 'status')?.field_value_text || '',
      reference: entity.dynamic_data?.find((d: any) => d.field_name === 'reference')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total GL Journals',
      value: gl_journals.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: BookOpen
    },
    {
      title: 'Active GL Journals',
      value: gl_journals.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: gl_journals.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'GL Journal Name', sortable: true },
    { key: 'journal_number', label: 'Journal number', sortable: true },
    { key: 'description', label: 'Description', sortable: true },
    { key: 'journal_date', label: 'Journal date', sortable: true },
    { key: 'total_debit', label: 'Total debit', sortable: true },
    { key: 'total_credit', label: 'Total credit', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search GL Journals', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'journal_number', label: 'Journal Number', type: 'select', options: [
        { value: '', label: 'All Journal Numbers' },
        ...Array.from(new Set(gl_journals.map(item => item.journal_number).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'description', label: 'Description', type: 'select', options: [
        { value: '', label: 'All Descriptions' },
        ...Array.from(new Set(gl_journals.map(item => item.description).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddGLJournal = async (gl_journalData: any) => {
    try {
      const result = await gl_journalData.create({
        entity_type: 'GL_JOURNAL',
        entity_name: gl_journalData.entity_name,
        smart_code: GL_JOURNAL_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, gl_journalData)

      // Emit creation event for audit trail
      await gl_journalData.emitEvent(GL_JOURNAL_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: gl_journalData
      })

      setShowAddModal(false)
      console.log('✅ GL Journal created successfully')
    } catch (error) {
      console.error('❌ Error adding gl_journal:', error)
    }
  }

  const handleEditGLJournal = async (gl_journalData: any) => {
    if (!currentGLJournal) return
    
    try {
      await gl_journalData.update(currentGLJournal.entity_id!, {
        entity_name: gl_journalData.entity_name
      }, gl_journalData)

      // Emit update event
      await gl_journalData.emitEvent(GL_JOURNAL_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentGLJournal.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: gl_journalData
      })

      setShowEditModal(false)
      setCurrentGLJournal(null)
      console.log('✅ GL Journal updated successfully')
    } catch (error) {
      console.error('❌ Error updating gl_journal:', error)
    }
  }

  const handleDeleteGLJournal = async () => {
    if (!gl_journalToDelete) return
    
    try {
      await gl_journalData.delete(gl_journalToDelete.entity_id!)

      // Emit deletion event
      await gl_journalData.emitEvent(GL_JOURNAL_SMART_CODES.EVENT_DELETED, {
        entity_id: gl_journalToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: gl_journalToDelete.entity_name
      })

      setShowDeleteModal(false)
      setGLJournalToDelete(null)
      console.log('✅ GL Journal deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting gl_journal:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access GL Journals.</p>
      </div>
    )
  }

  if (gl_journalData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading GL Journals...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="GL Journals"
      subtitle={`${gl_journals.length} total gl_journals`}
      primaryColor="#7c3aed"
      accentColor="#6d28d9"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#7c3aed' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={gl_journals}
        columns={columns}
        selectedRows={selectedGLJournals}
        onRowSelect={setSelectedGLJournals}
        onRowClick={(gl_journal) => {
          setCurrentGLJournal(gl_journal)
          setShowEditModal(true)
        }}
        showBulkActions={selectedGLJournals.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedGLJournals) {
                await gl_journalData.delete(id.toString())
              }
              setSelectedGLJournals([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(gl_journal) => (
          <MobileCard key={gl_journal.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{gl_journal.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentGLJournal(gl_journal)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setGLJournalToDelete(gl_journal)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Journal Number:</span>{' '}
              {gl_journal.journal_number || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Description:</span>{' '}
              {gl_journal.description || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Journal Date:</span>{' '}
              {gl_journal.journal_date || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Total Debit:</span>{' '}
              {gl_journal.total_debit || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {gl_journal.created_at ? new Date(gl_journal.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#7c3aed' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <GLJournalModal
          title="Add New GL Journal"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddGLJournal}
          dynamicFields={gl_journalData.dynamicFieldsConfig || []}
          businessRules={{"balance_validation":true,"posting_controls":true,"audit_trail":true}}
        />
      )}

      {showEditModal && currentGLJournal && (
        <GLJournalModal
          title="Edit GL Journal"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentGLJournal(null)
          }}
          onSave={handleEditGLJournal}
          initialData={currentGLJournal}
          dynamicFields={gl_journalData.dynamicFieldsConfig || []}
          businessRules={{"balance_validation":true,"posting_controls":true,"audit_trail":true}}
        />
      )}

      {showDeleteModal && gl_journalToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete GL Journal</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{gl_journalToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setGLJournalToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteGLJournal}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise GL Journal Modal Component
 * Enhanced with business rules and validation
 */
interface GLJournalModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: GLJournal
  dynamicFields: any[]
  businessRules: any
}

function GLJournalModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: GLJournalModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof GLJournal] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'GL Journal name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                GL Journal Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Journal Number 
              </label>
              <input
                type="text"
                value={formData.journal_number}
                onChange={(e) => setFormData({ ...formData, journal_number: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.journal_number ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.journal_number && (
                <p className="mt-1 text-sm text-red-600">{errors.journal_number}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Description 
              </label>
              <input
                type="text"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.description ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.description && (
                <p className="mt-1 text-sm text-red-600">{errors.description}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Journal Date 
              </label>
              <input
                type="text"
                value={formData.journal_date}
                onChange={(e) => setFormData({ ...formData, journal_date: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.journal_date ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.journal_date && (
                <p className="mt-1 text-sm text-red-600">{errors.journal_date}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Total Debit 
              </label>
              <input
                type="text"
                value={formData.total_debit}
                onChange={(e) => setFormData({ ...formData, total_debit: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.total_debit ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.total_debit && (
                <p className="mt-1 text-sm text-red-600">{errors.total_debit}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Total Credit 
              </label>
              <input
                type="text"
                value={formData.total_credit}
                onChange={(e) => setFormData({ ...formData, total_credit: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.total_credit ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.total_credit && (
                <p className="mt-1 text-sm text-red-600">{errors.total_credit}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Status 
              </label>
              <input
                type="text"
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.status ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.status && (
                <p className="mt-1 text-sm text-red-600">{errors.status}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Reference 
              </label>
              <input
                type="text"
                value={formData.reference}
                onChange={(e) => setFormData({ ...formData, reference: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.reference ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.reference && (
                <p className="mt-1 text-sm text-red-600">{errors.reference}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#7c3aed' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}