/**
 * Leads List Report
 * 
 * Generated by HERA Hook-Driven Module Generator
 * Uses Fiori++ List Report template with glassmorphism design
 */

'use client'

import React, { useState } from 'react'
import { useState } from 'react'
import { ColumnDef } from '@tanstack/react-table'
import { useLeadss, useLeadsMutations } from '@/lib/hooks/useLeadss'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import HERAMasterDataTemplate from '@/components/hera/HERAMasterDataTemplate'
import { HERAListReport, QuickFilters } from '@/components/ui-kit/floorplans/list-report'
import { StatusBadge } from '@/components/ui-kit/primitives'
import { Button } from '@/components/ui/button'
import { Target, Plus, Mail, Search } from 'lucide-react'

// Type definitions
interface Leads {
  entity_id: string
  entity_name: string
  entity_type: 'LEAD'
  smart_code: string
  created_at: string
  updated_at: string
  created_by: string
  updated_by: string
  dynamic_fields?: Record<string, {
    field_value_text?: string
    field_value_number?: number
    field_value_boolean?: boolean
    field_value_json?: any
    smart_code: string
  }>
}

// Column definitions for Leads data grid
const leadsColumns: ColumnDef<Leads>[] = [
  {
    accessorKey: 'entity_name',
    header: 'Leads Name',
    cell: ({ row }) => (
      <div className="flex items-center gap-3">
        <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-blue-500 to-blue-600 flex items-center justify-center">
          <Target className="w-4 h-4 text-white" />
        </div>
        <div>
          <div className="font-medium">{row.original.entity_name}</div>
          <div className="text-xs text-gray-500">{row.original.entity_id}</div>
        </div>
      </div>
    )
  },
  {
    accessorKey: 'smart_code',
    header: 'Smart Code',
    cell: ({ row }) => (
      <code className="text-xs bg-gray-100/80 dark:bg-gray-800/80 px-2 py-1 rounded backdrop-blur-sm">
        {row.original.smart_code}
      </code>
    )
  },
  {
    accessorKey: 'created_at',
    header: 'Created',
    cell: ({ row }) => (
      <div className="text-sm">
        {new Date(row.original.created_at).toLocaleDateString()}
      </div>
    )
  },
  {
    accessorKey: 'updated_at', 
    header: 'Last Updated',
    cell: ({ row }) => (
      <div className="text-sm">
        {new Date(row.original.updated_at).toLocaleDateString()}
      </div>
    )
  }
]

// Master data form configuration for create/edit
const LEAD_SECTIONS = [
  {
    id: 'basic',
    label: 'Basic Information',
    icon: Target,
    required: true,
    description: 'Enter basic leads information and categorization'
  },
  {
    id: 'contact',
    label: 'Contact Details', 
    icon: Mail,
    required: false,
    description: 'Contact information and communication preferences'
  },
  {
    id: 'business',
    label: 'Business Data',
    icon: Search,
    required: false,
    description: 'Business-specific fields and classifications'
  }
]

const LEAD_FIELDS = [
  {
    id: 'entity_name',
    label: 'Leads Name',
    type: 'text' as const,
    required: true,
    placeholder: 'Enter leads name',
    section: 'basic',
    validation: (value: string) => {
      return !value.trim() ? 'Name is required' : null
    }
  },
  {
    id: 'entity_code',
    label: 'Leads Code',
    type: 'text' as const,
    required: true,
    placeholder: 'Auto-generated from name',
    section: 'basic'
  },
  {
    id: 'email',
    label: 'Email Address',
    type: 'email' as const,
    required: false,
    placeholder: 'contact@example.com',
    section: 'contact',
    validation: (value: string) => {
      if (!value) return null
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
      return !emailRegex.test(value) ? 'Please enter a valid email address' : null
    }
  },
  {
    id: 'phone',
    label: 'Phone Number',
    type: 'phone' as const,
    required: false,
    placeholder: '+1 (555) 123-4567',
    section: 'contact'
  }
]

export default function LeadsPage() {
  const [showCreateForm, setShowCreateForm] = useState(false)
  const [searchValue, setSearchValue] = useState('')
  const [statusFilter, setStatusFilter] = useState('all')

  // Handle create form submission using HERAMasterDataTemplate
  const handleCreateLeads = async (formData: Record<string, any>) => {
    // Generate HERA DNA smart code
    const smartCode = `HERA.CRM.LEAD.${formData.entity_code || 'ENTITY'}.v1`
    
    // Prepare dynamic fields from form data
    const dynamicFields = []
    
    if (formData.email) {
      dynamicFields.push({
        field_name: 'email',
        field_type: 'email',
        field_value_text: formData.email,
        smart_code: `HERA.CRM.LEAD.DYN.EMAIL.v1`
      })
    }
    
    if (formData.phone) {
      dynamicFields.push({
        field_name: 'phone',
        field_type: 'phone',
        field_value_text: formData.phone,
        smart_code: `HERA.CRM.LEAD.DYN.PHONE.v1`
      })
    }

    // This will be wired to HERA hooks when ready
    console.log('Creating leads:', { smartCode, formData, dynamicFields })
    
    setShowCreateForm(false)
  }

  // Show create form using HERAMasterDataTemplate
  if (showCreateForm) {
    return (
      <HERAMasterDataTemplate
        entityType="leads"
        entityLabel="Leads"
        sections={LEAD_SECTIONS}
        fields={LEAD_FIELDS}
        backUrl="/crm/leads"
        onSubmit={handleCreateLeads}
      />
    )
  }

  // Use Fiori++ List Report template
  return (
    <HERAListReport
      title="Leadss"
      entityType="Leads"
      useListHook={useLeadss}
      useMutationsHook={useLeadsMutations}
      onCreateNew={() => setShowCreateForm(true)}
      customColumns={leadsColumns}
      searchValue={searchValue}
      onSearchChange={setSearchValue}
      filters={
        <QuickFilters
          statusOptions={[
            { value: 'active', label: 'Active' },
            { value: 'inactive', label: 'Inactive' },
            { value: 'pending', label: 'Pending' }
          ]}
          onStatusChange={setStatusFilter}
        />
      }
      onView={(leads) => {
        console.log('View leads:', leads)
        // Navigate to object page when implemented
      }}
      onEdit={(leads) => {
        console.log('Edit leads:', leads)
        // Open edit form when implemented
      }}
      emptyState={{
        icon: <Target className="w-8 h-8 text-gray-400" />,
        title: `No leadss found`,
        description: `Get started by creating your first leads.`,
        action: (
          <Button onClick={() => setShowCreateForm(true)}>
            <Plus className="w-4 h-4 mr-2" />
            Create Leads
          </Button>
        )
      }}
      showSelection={true}
      showExport={true}
      showFilters={true}
    />
  )
}
