-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.core_clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  client_name character varying NOT NULL UNIQUE,
  client_code character varying NOT NULL UNIQUE,
  client_type character varying NOT NULL,
  parent_client_id uuid,
  headquarters_country character varying,
  incorporation_country character varying,
  stock_exchange character varying,
  ticker_symbol character varying,
  legal_entity_identifier character varying,
  tax_identification_number character varying,
  regulatory_status character varying,
  compliance_requirements jsonb DEFAULT '{}'::jsonb,
  primary_contact_email character varying,
  primary_contact_phone character varying,
  website character varying,
  primary_address jsonb,
  fiscal_year_end date,
  reporting_currency character varying DEFAULT 'USD'::character varying,
  base_timezone character varying DEFAULT 'UTC'::character varying,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying, 'merged'::character varying, 'acquired'::character varying]::text[])),
  subscription_tier character varying DEFAULT 'enterprise'::character varying,
  client_settings jsonb DEFAULT '{}'::jsonb,
  ai_insights jsonb DEFAULT '{}'::jsonb,
  ai_classification character varying,
  ai_confidence numeric DEFAULT 0.0000,
  ai_risk_profile jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  version integer DEFAULT 1,
  CONSTRAINT core_clients_pkey PRIMARY KEY (id),
  CONSTRAINT core_clients_parent_client_id_fkey FOREIGN KEY (parent_client_id) REFERENCES public.core_clients(id)
);
CREATE TABLE public.core_dynamic_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  entity_id uuid NOT NULL,
  field_name character varying NOT NULL,
  field_label character varying,
  field_description text,
  field_type character varying NOT NULL CHECK (field_type::text = ANY (ARRAY['text'::character varying, 'number'::character varying, 'boolean'::character varying, 'date'::character varying, 'datetime'::character varying, 'json'::character varying, 'file'::character varying]::text[])),
  field_category character varying,
  field_value text,
  field_value_number numeric,
  field_value_boolean boolean,
  field_value_date date,
  field_value_datetime timestamp with time zone,
  field_value_json jsonb,
  display_order integer DEFAULT 0,
  is_required boolean DEFAULT false,
  is_searchable boolean DEFAULT false,
  validation_rules jsonb DEFAULT '{}'::jsonb,
  ai_enhanced_value text,
  ai_confidence numeric DEFAULT 0.0000,
  validation_status character varying DEFAULT 'pending'::character varying CHECK (validation_status::text = ANY (ARRAY['valid'::character varying, 'invalid'::character varying, 'pending'::character varying, 'ai_enhanced'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT core_dynamic_data_pkey PRIMARY KEY (id),
  CONSTRAINT core_dynamic_data_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id),
  CONSTRAINT core_dynamic_data_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.core_entities(id)
);
CREATE TABLE public.core_entities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  entity_type character varying NOT NULL,
  entity_name character varying NOT NULL,
  entity_code character varying,
  entity_category character varying,
  entity_subcategory character varying,
  description text,
  tags ARRAY,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'archived'::character varying, 'draft'::character varying]::text[])),
  effective_date date DEFAULT CURRENT_DATE,
  expiry_date date,
  metadata jsonb DEFAULT '{}'::jsonb,
  ai_confidence numeric DEFAULT 0.0000,
  ai_classification character varying,
  ai_tags ARRAY,
  parent_entity_id uuid,
  hierarchy_level integer DEFAULT 0,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  version integer DEFAULT 1,
  CONSTRAINT core_entities_pkey PRIMARY KEY (id),
  CONSTRAINT core_entities_parent_entity_id_fkey FOREIGN KEY (parent_entity_id) REFERENCES public.core_entities(id),
  CONSTRAINT core_entities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id)
);
CREATE TABLE public.core_organizations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_name character varying NOT NULL,
  organization_code character varying NOT NULL UNIQUE,
  organization_type character varying NOT NULL,
  industry character varying,
  business_size character varying,
  tax_id character varying,
  registration_number character varying,
  email character varying,
  phone character varying,
  website character varying,
  address jsonb,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying, 'trial'::character varying]::text[])),
  subscription_tier character varying DEFAULT 'starter'::character varying,
  settings jsonb DEFAULT '{}'::jsonb,
  ai_insights jsonb DEFAULT '{}'::jsonb,
  ai_classification character varying,
  ai_confidence numeric DEFAULT 0.0000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  version integer DEFAULT 1,
  client_id uuid NOT NULL,
  legal_entity_name character varying,
  subsidiary_type character varying,
  country_code character varying,
  region character varying,
  regulatory_requirements jsonb DEFAULT '{}'::jsonb,
  intercompany_code character varying,
  consolidation_method character varying DEFAULT 'full'::character varying,
  functional_currency character varying DEFAULT 'USD'::character varying,
  reporting_currency character varying DEFAULT 'USD'::character varying,
  CONSTRAINT core_organizations_pkey PRIMARY KEY (id),
  CONSTRAINT core_organizations_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.core_clients(id)
);
CREATE TABLE public.core_relationships (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  source_entity_id uuid NOT NULL,
  target_entity_id uuid NOT NULL,
  relationship_type character varying NOT NULL,
  relationship_label character varying,
  relationship_strength numeric DEFAULT 1.0000,
  is_bidirectional boolean DEFAULT false,
  is_active boolean DEFAULT true,
  hierarchy_level integer DEFAULT 0,
  workflow_state character varying,
  workflow_step integer DEFAULT 0,
  relationship_data jsonb DEFAULT '{}'::jsonb,
  business_rules jsonb DEFAULT '{}'::jsonb,
  effective_date date DEFAULT CURRENT_DATE,
  expiry_date date,
  ai_discovered boolean DEFAULT false,
  ai_confidence numeric DEFAULT 0.0000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT core_relationships_pkey PRIMARY KEY (id),
  CONSTRAINT core_relationships_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id),
  CONSTRAINT core_relationships_target_entity_id_fkey FOREIGN KEY (target_entity_id) REFERENCES public.core_entities(id),
  CONSTRAINT core_relationships_source_entity_id_fkey FOREIGN KEY (source_entity_id) REFERENCES public.core_entities(id)
);
CREATE TABLE public.gl_chart_of_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  account_code character varying NOT NULL CHECK (account_code::text ~ '^[1-9][0-9]{6}$'::text),
  account_name character varying NOT NULL,
  account_type character varying NOT NULL CHECK (account_type::text = ANY (ARRAY['assets'::character varying, 'liabilities'::character varying, 'equity'::character varying, 'revenue'::character varying, 'cost_of_sales'::character varying, 'direct_expenses'::character varying, 'indirect_expenses'::character varying, 'tax_extraordinary'::character varying, 'statistical'::character varying]::text[])),
  account_category character varying,
  parent_account_code character varying,
  is_active boolean DEFAULT true,
  description text,
  ai_usage_pattern jsonb DEFAULT '{}'::jsonb,
  ai_suggested_transactions integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT gl_chart_of_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT gl_chart_of_accounts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id)
);
CREATE TABLE public.universal_transaction_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  transaction_id uuid NOT NULL,
  organization_id uuid NOT NULL,
  entity_id uuid,
  line_description text NOT NULL,
  line_order integer NOT NULL DEFAULT 1,
  quantity numeric DEFAULT 1.000000,
  unit_of_measure character varying,
  unit_price numeric DEFAULT 0.0000,
  line_amount numeric DEFAULT 0.0000,
  discount_percentage numeric DEFAULT 0.0000,
  discount_amount numeric DEFAULT 0.0000,
  tax_code character varying,
  tax_percentage numeric DEFAULT 0.0000,
  tax_amount numeric DEFAULT 0.0000,
  net_line_amount numeric DEFAULT ((line_amount - discount_amount) + tax_amount),
  gl_account_code character varying,
  cost_center character varying,
  department character varying,
  project_code character varying,
  delivery_date date,
  service_period_start date,
  service_period_end date,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  ai_gl_suggestion character varying,
  ai_confidence numeric DEFAULT 0.0000,
  ai_cost_prediction numeric,
  ai_margin_analysis jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT universal_transaction_lines_pkey PRIMARY KEY (id),
  CONSTRAINT universal_transaction_lines_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES public.universal_transactions(id),
  CONSTRAINT universal_transaction_lines_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id),
  CONSTRAINT universal_transaction_lines_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.core_entities(id)
);
CREATE TABLE public.universal_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  organization_id uuid NOT NULL,
  transaction_type character varying NOT NULL,
  transaction_number character varying NOT NULL,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  reference_number character varying,
  external_reference character varying,
  source_entity_id uuid,
  target_entity_id uuid,
  total_amount numeric DEFAULT 0.0000,
  tax_amount numeric DEFAULT 0.0000,
  discount_amount numeric DEFAULT 0.0000,
  net_amount numeric DEFAULT ((total_amount - discount_amount) + tax_amount),
  currency character varying DEFAULT 'USD'::character varying,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'pending'::character varying, 'approved'::character varying, 'processing'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'reversed'::character varying]::text[])),
  workflow_state character varying,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  department character varying,
  project_code character varying,
  cost_center character varying,
  due_date date,
  completed_date date,
  description text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  attachments jsonb DEFAULT '[]'::jsonb,
  ai_insights jsonb DEFAULT '{}'::jsonb,
  ai_risk_score numeric DEFAULT 0.0000,
  ai_anomaly_score numeric DEFAULT 0.0000,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  version integer DEFAULT 1,
  is_intercompany boolean DEFAULT false,
  intercompany_source_org uuid,
  intercompany_target_org uuid,
  intercompany_reference character varying,
  elimination_required boolean DEFAULT false,
  CONSTRAINT universal_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT universal_transactions_target_entity_id_fkey FOREIGN KEY (target_entity_id) REFERENCES public.core_entities(id),
  CONSTRAINT universal_transactions_intercompany_target_org_fkey FOREIGN KEY (intercompany_target_org) REFERENCES public.core_organizations(id),
  CONSTRAINT universal_transactions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.core_organizations(id),
  CONSTRAINT universal_transactions_source_entity_id_fkey FOREIGN KEY (source_entity_id) REFERENCES public.core_entities(id),
  CONSTRAINT universal_transactions_intercompany_source_org_fkey FOREIGN KEY (intercompany_source_org) REFERENCES public.core_organizations(id)
);