smart_code: HERA.UNIV.WF.DEFINITION.V1
intent: AP Bill Approval workflow definition for finance operations
definition:
  code: AP_BILL_APPROVAL
  states: [INGESTED, MATCH_2W, REVIEW, APPROVED, POSTED, PAID, REJECTED]
  transitions:
    - from: INGESTED
      to: MATCH_2W
      by: [system]
      guards:
        - HERA.FIN.AP.BILL.VENDOR.VALIDATE.V1
        - HERA.FIN.AP.BILL.MATCH.PO.V1
    - from: MATCH_2W
      to: REVIEW
      by: [system]
    - from: REVIEW
      to: APPROVED
      by: [ap_manager]
    - from: APPROVED
      to: POSTED
      by: [system]
      effects:
        - HERA.FIN.POSTING.GL.JOURNAL.V1
    - from: POSTED
      to: PAID
      by: [ap_clerk]
      effects:
        - HERA.FIN.AP.PAYMENT.V1
    - from: REVIEW
      to: REJECTED
      by: [ap_manager]
  timers:
    - on_enter: REVIEW
      minutes: 2880                                # 48 hours
      on_fire: HERA.UNIV.TASK.ESCALATE.V1
      name: review_timeout