smart_code: HERA.UNIV.WF.INSTANCES.LIST.V1
intent: List workflow instances with filtering and pagination.
scope:
  in_scope:
    - query instances from view
    - apply filters and pagination
    - return formatted results
    - maintain org isolation
  out_of_scope:
    - instance modification
    - state changes
    - complex aggregations
preconditions:
  - permissions: [$PROFILE.required_role_read] or instance owner
  - organization_id provided for isolation
invariants:
  - read-only operation
  - org isolation enforced
  - pagination limits respected
inputs:
  required:
    - organization_id: uuid
  optional:
    - definition_code: string                      # filter by workflow type
    - current_state: string                        # filter by state
    - owner_team: string                           # filter by owning team
    - owner_user_id: uuid                          # filter by owning user
    - paused: boolean                              # filter by pause status
    - overdue: boolean                             # filter by SLA breach
    - created_after: timestamp                     # date range filter
    - created_before: timestamp                    # date range filter
    - limit: number                                # pagination limit (default 50, max 500)
    - offset: number                               # pagination offset
    - sort_by: string                              # sort field (created_at, updated_at, sla_at)
    - sort_order: enum[asc, desc]                  # sort direction
happy_path:
  - step: build query against wf_instances_view with organization_id filter
  - step: apply optional filters if provided
  - step: apply pagination (limit/offset) and sorting
  - step: execute query and format results
  - step: include pagination metadata in response
outputs:
  response:
    instances: array
      - instance_id: uuid
        definition_code: string
        definition_version: string
        current_state: string
        subject_ref_json: object
        sla_at: timestamp
        paused: boolean
        owner_team: string
        owner_user_id: uuid
        status: string
        created_at: timestamp
        updated_at: timestamp
    pagination:
      total_count: number
      limit: number
      offset: number
      has_more: boolean
    filters_applied: object
errors:
  - code: INVALID_FILTER
    when: filter parameters are invalid
    action: return 400 with validation details
  - code: INVALID_PAGINATION
    when: limit/offset are out of bounds
    action: return 400 with valid ranges
  - code: PERMISSION_DENIED
    when: user lacks read permissions
    action: return 403
observability:
  logs:
    - instances_listed: { organization_id, filter_count, result_count }
  audit_json: false                                # read-only, high frequency
  metrics:
    - instance_list_requests
    - instance_list_result_size
    - instance_list_duration
example_payload:
  organization_id: "123e4567-e89b-12d3-a456-426614174000"
  definition_code: "LEAVE_APPROVAL"
  current_state: "MANAGER_REVIEW"
  overdue: true
  limit: 25
  sort_by: "sla_at"
  sort_order: "asc"
checks:
  - description: ensure org isolation in all queries
  - description: validate pagination parameters
  - description: verify filter combinations are valid