smart_code: HERA.CRM.REPORTS.CORE.DEFS.v1
reports:
  - report_code: HERA.CRM.REPORT.PIPELINE_BY_STAGE.CORE.v1
    description: "Opportunity pipeline by stage"
    params_schema:
      as_of: { type: date }
    query:
      template: |
        SELECT (SELECT value_text FROM core_dynamic_data WHERE entity_id = o.id AND key = 'opportunity.stage' AND organization_id = $org LIMIT 1) AS stage,
               COUNT(*) AS opp_count,
               SUM((SELECT value_number FROM core_dynamic_data WHERE entity_id = o.id AND key = 'opportunity.amount' AND organization_id = $org LIMIT 1)) AS total_amount
        FROM core_entities o
        WHERE o.organization_id = $org AND o.entity_type = 'opportunity'
        GROUP BY stage
        ORDER BY opp_count DESC

  - report_code: HERA.CRM.REPORT.ACTIVITIES_BY_OWNER.CORE.v1
    description: "Activities count by assigned owner"
    params_schema:
      from: { type: date }
      to:   { type: date }
    query:
      template: |
        SELECT own.entity_name AS owner_name,
               COUNT(*)        AS activity_count
        FROM universal_transactions t
        LEFT JOIN core_entities own ON own.id = t.reference_entity_id AND own.organization_id = $org
        WHERE t.organization_id = $org
          AND t.transaction_type = 'crm_activity'
          AND t.transaction_date BETWEEN $from AND $to
        GROUP BY owner_name
        ORDER BY activity_count DESC

  - report_code: HERA.CRM.REPORT.LEAD_CONVERSION.CORE.v1
    description: "Lead status distribution (conversion)"
    params_schema:
      as_of: { type: date }
    query:
      template: |
        SELECT (SELECT value_text FROM core_dynamic_data WHERE entity_id = l.id AND key = 'lead.status' AND organization_id = $org LIMIT 1) AS status,
               COUNT(*) AS leads
        FROM core_entities l
        WHERE l.organization_id = $org AND l.entity_type = 'lead'
        GROUP BY status
        ORDER BY leads DESC
