'use client'

import React, { useState } from 'react'
import { Card } from '@/src/components/ui/card'
import { Button } from '@/src/components/ui/button'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/src/components/ui/tabs'
import { BarChart, Bar, LineChart, Line, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer
} from 'recharts'
import { TrendingUp, Trophy, Brain, DollarSign, Target, Clock, AlertCircle, FileText
} from 'lucide-react'
import { useFurnitureOrg } from '@/src/components/furniture/FurnitureOrgContext'
import FurniturePageHeader from '@/src/components/furniture/FurniturePageHeader'
import { StatCardGrid } from '@/src/lib/dna/components/ui/stat-card-dna'
import { FurnitureStatCard } from '@/src/components/furniture/FurnitureStatCard'
import TenderListTable from '@/src/components/furniture/tender/TenderListTable'


export const dynamic = 'force-dynamic' // Mock data for charts
  const monthlyBidData = [ { month: 'Sep', submitted: 12, won: 5, lost: 7, value: 45 }, { month: 'Oct', submitted: 15, won: 7, lost: 8, value: 62 }, { month: 'Nov', submitted: 18, won: 8, lost: 10, value: 78 }, { month: 'Dec', submitted: 22, won: 10, lost: 12, value: 95 }, { month: 'Jan', submitted: 24, won: 11, lost: 13, value: 102 }
] const winRateByCategory = [ { category: 'Teak', winRate: 65, totalBids: 15 }, { category: 'Rosewood', winRate: 45, totalBids: 12 }, { category: 'Sandalwood', winRate: 38, totalBids: 8 }, { category: 'Mixed Timber', winRate: 55, totalBids: 20 }, { category: 'Bamboo', winRate: 72, totalBids: 10 }
] const competitorAnalysis = [ { name: 'ABC Timber', share: 28, color: '#ff6b6b' }, { name: 'XYZ Wood', share: 22, color: '#4ecdc4' }, { name: 'PQR Timbers', share: 18, color: '#45b7d1' }, { name: 'Kerala Furniture', share: 15, color: '#f9ca24' }, { name: 'Others', share: 17, color: '#95a5a6' }
] const dashboardStats = [ { label: 'YTD Win Rate', value: '42%', change: '+5% vs last year', trend: 'up' as const, icon: Trophy, gradient: 'from-green-500 to-emerald-500' }, { label: 'Total Contract Value', value: '₹3.2Cr', change: '65 tenders won', trend: 'up' as const, icon: DollarSign, gradient: 'from-blue-500 to-cyan-500' }, { label: 'AI Success Rate', value: '78%', change: 'Strategy accuracy', trend: 'up' as const, icon: Brain, gradient: 'from-[var(--color-accent-teal)] to-[var(--color-accent-teal)]' }, { label: 'Avg Margin', value: '12.5%', change: 'Optimal pricing', trend: 'neutral' as const, icon: Target, gradient: 'from-[var(--color-accent-teal)] to-[var(--color-accent-teal)]' }
]

export default function TenderDashboardPage() {
  const { organizationId, organizationName, orgLoading } = useFurnitureOrg()

const [activeTab, setActiveTab] = useState('overview') if (orgLoading) {
  return (
    <div className="min-h-screen bg-[var(--color-body)] flex items-center justify-center"> <div className="text-center"> <div className="inline-flex items-center space-x-2"> <div className="w-8 h-8 border-4 border-[var(--color-accent-indigo)] border-t-transparent rounded-full animate-spin"></div> <p className="text-[var(--color-text-secondary)]">Loading tender dashboard...</p> </div> </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-[var(--color-body)]"> <div className="p-6 space-y-6"> {/* Header */} <FurniturePageHeader title="Tender Analytics Dashboard" subtitle="Performance insights and competitive analysis" actions={ <Button variant="outline" size="sm"> Export Report </Button> } /> {/* Key Metrics */} <div className="space-y-4"> <h2 className="bg-[var(--color-body)] text-xl font-semibold text-[var(--color-text-primary)]">Performance Overview</h2> <StatCardGrid> {dashboardStats.map(stat => ( <FurnitureStatCard key={stat.label} {...stat} /> ))} </StatCardGrid> </div> {/* Analytics Tabs */} <Tabs value={activeTab} onValueChange={setActiveTab} className="bg-[var(--color-body)] space-y-4"> <TabsList className="bg-[var(--color-body)]/50 backdrop-blur-sm"> <TabsTrigger value="overview">Overview</TabsTrigger> <TabsTrigger value="trends">Bid Trends</TabsTrigger> <TabsTrigger value="competition">Competition</TabsTrigger> <TabsTrigger value="ai-insights">AI Insights</TabsTrigger> <TabsTrigger value="all-tenders">All Tenders</TabsTrigger> </TabsList> <TabsContent value="overview" className="bg-[var(--color-body)] space-y-6"> {/* Monthly Bid Performance */} <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-[var(--color-body)]/70 backdrop-blur-sm border-[var(--color-border)]/50"> <h3 className="bg-[var(--color-body)] text-lg font-semibold text-[var(--color-text-primary)] mb-4">Monthly Bid Performance</h3> <ResponsiveContainer width="100%" height={300}> <BarChart data={monthlyBidData}> <CartesianGrid strokeDasharray="3 3" stroke="#374151" /> <XAxis dataKey="month" stroke="#9CA3AF" /> <YAxis stroke="#9CA3AF" /> <Tooltip contentStyle={{ backgroundColor: '#1F2937', border: '1px solid #374151', borderRadius: '8px' }
    } /> <Legend /> <Bar dataKey="won" fill="#10B981" name="Won" /> <Bar dataKey="lost" fill="#EF4444" name="Lost" /> </BarChart> </ResponsiveContainer> </Card> {/* Win Rate by Category */} <div className="grid grid-cols-1 md:grid-cols-2 gap-4"> <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-[var(--color-body)]/70 backdrop-blur-sm border-[var(--color-border)]/50"> <h3 className="bg-[var(--color-body)] text-lg font-semibold text-[var(--color-text-primary)] mb-4">Win Rate by Wood Type</h3> <div className="space-y-3"> {winRateByCategory.map(item => ( <div key={item.category} className="bg-[var(--color-body)] space-y-2"> <div className="flex items-center justify-between"> <span className="text-sm text-[var(--color-text-secondary)]">{item.category}</span> <span className="text-sm font-medium text-[var(--color-text-primary)]">{item.winRate}%</span> </div> <div className="h-2 bg-muted-foreground/10 rounded-full overflow-hidden"> <div className="h-full bg-gradient-to-r from-[var(--color-accent-teal)] to-[var(--color-accent-teal)] transition-all" style={{ width: `${item.winRate}%` }
    } /> </div> <p className="text-xs text-[var(--color-text-secondary)]">{item.totalBids} bids submitted</p>
      </div>
    ))} </div> </Card> <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-[var(--color-body)]/70 backdrop-blur-sm border-[var(--color-border)]/50"> <h3 className="bg-[var(--color-body)] text-lg font-semibold text-[var(--color-text-primary)] mb-4">Market Share Analysis</h3> <ResponsiveContainer width="100%" height={250}> <PieChart> <Pie data={competitorAnalysis} cx="50%" cy="50%" innerRadius={60} outerRadius={90} paddingAngle={5} dataKey="share" > {competitorAnalysis.map((entry, index) => ( <Cell key={`cell-${index}`} fill={entry.color} /> ))} </Pie> <Tooltip contentStyle={{ backgroundColor: '#1F2937', border: '1px solid #374151', borderRadius: '8px' }
    } /> </PieChart> </ResponsiveContainer> <div className="grid grid-cols-2 gap-2 mt-4"> {competitorAnalysis.map(item => ( <div key={item.name} className="bg-[var(--color-body)] flex items-center gap-2"> <div className="bg-[var(--color-body)] w-3 h-3 rounded-full" style={{ backgroundColor: item.color }
    } /> <span className="text-xs text-[var(--color-text-secondary)]"> {item.name}: {item.share}% </span>
      </div>
    ))} </div> </Card> </div> {/* Recent Alerts */} <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-gradient-to-br from-amber-900/20 to-orange-900/20 border-amber-700/50"> <div className="flex items-start gap-4"> <div className="p-3 rounded-xl bg-[var(--color-accent-indigo)]/20"> <AlertCircle className="h-6 w-6 text-[#37353E]" /> </div> <div className="flex-1"> <h4 className="bg-[var(--color-body)] font-semibold text-[var(--color-text-primary)]">Upcoming Tender Closures</h4> <p className="text-sm text-gray-300 mt-1"> 3 tenders closing in the next 7 days. KFD/2025/WOOD/001 requires immediate attention for bid submission. </p> <div className="flex gap-2 mt-3"> <Button size="sm" variant="secondary"> View Tenders </Button> <Button size="sm" variant="ghost"> Set Reminders </Button> </div> </div> </div> </Card> </TabsContent> <TabsContent value="trends" className="bg-[var(--color-body)] space-y-6"> <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-[var(--color-body)]/70 backdrop-blur-sm border-[var(--color-border)]/50"> <h3 className="bg-[var(--color-body)] text-lg font-semibold text-[var(--color-text-primary)] mb-4">Contract Value Trend</h3> <ResponsiveContainer width="100%" height={350}> <LineChart data={monthlyBidData}> <CartesianGrid strokeDasharray="3 3" stroke="#374151" /> <XAxis dataKey="month" stroke="#9CA3AF" /> <YAxis stroke="#9CA3AF" /> <Tooltip contentStyle={{ backgroundColor: '#1F2937', border: '1px solid #374151', borderRadius: '8px' }
    } /> <Legend /> <Line type="monotone" dataKey="value" stroke="#F59E0B" strokeWidth={3} dot={{ fill: '#F59E0B', r: 6 }
    } name="Contract Value (₹ Lakhs)" /> </LineChart> </ResponsiveContainer> </Card> </TabsContent> <TabsContent value="ai-insights" className="bg-[var(--color-body)] space-y-6"> <Card className="bg-[var(--color-surface-raised)] border-[var(--color-border)] p-6 bg-gradient-to-br from-[var(--color-accent-teal)]-900/20 to-[var(--color-accent-teal)]-900/20 border-[var(--color-accent-teal)]-700/50"> <div className="flex items-start gap-4 mb-6"> <div className="p-3 rounded-xl bg-[var(--color-accent-indigo)]/20"> <Brain className="h-6 w-6 text-[#37353E]" /> </div> <div className="flex-1"> <h3 className="bg-[var(--color-body)] text-lg font-semibold text-[var(--color-text-primary)]">AI Performance Analysis</h3> <p className="text-sm text-gray-300 mt-1"> Machine learning models achieving 78% accuracy in bid strategy recommendations </p> </div> </div> <div className="grid grid-cols-1 md:grid-cols-3 gap-4"> <div className="p-4 rounded-lg bg-muted-foreground/10/30"> <p className="text-sm text-[var(--color-text-secondary)]">Prediction Accuracy</p> <p className="text-2xl font-bold text-[var(--color-text-primary)] mt-1">78%</p> <p className="text-xs text-green-400 mt-1">+12% improvement</p> </div> <div className="p-4 rounded-lg bg-muted-foreground/10/30"> <p className="text-sm text-[var(--color-text-secondary)]">Revenue Impact</p> <p className="text-2xl font-bold text-[var(--color-text-primary)] mt-1">₹45L</p> <p className="text-xs text-[var(--color-text-secondary)] mt-1">Additional revenue from AI</p> </div> <div className="p-4 rounded-lg bg-muted-foreground/10/30"> <p className="text-sm text-[var(--color-text-secondary)]">Time Saved</p> <p className="text-2xl font-bold text-[var(--color-text-primary)] mt-1">120hrs</p> <p className="text-xs text-[var(--color-text-secondary)] mt-1">Monthly automation benefit</p> </div> </div> </Card> </TabsContent> <TabsContent value="all-tenders" className="bg-[var(--color-body)] space-y-6"> <TenderListTable /> </TabsContent> </Tabs> </div>
      </div>
    )
}
