smart_code: HERA.SYSTEM.SMART_CODE.REGISTRY_OVERLAY.v1
allocations:
  - { code: HERA.CRM.DEAL.OPPORTUNITY.v1,         status: active,   owner: crm@yourco }
  - { code: HERA.CRM.DEAL.STAGE_CHANGE.v1,        status: active,   owner: crm@yourco }
  - { code: HERA.CRM.DEAL.CLOSED_WON.v1,          status: active,   owner: crm@yourco }
  - { code: HERA.CRM.CONTACT.CUSTOMER.v1,         status: active,   owner: crm@yourco }
  - { code: HERA.CRM.COMPANY.ORGANIZATION.v1,     status: active,   owner: crm@yourco }
  - { code: HERA.CRM.ACTIVITY.MEETING.v1,         status: active,   owner: crm@yourco }
  - { code: HERA.CRM.COMMS.EMAIL.SENT.v1,         status: active,   owner: crm@yourco }
  - { code: HERA.CRM.COMMS.EMAIL.RECEIVED.v1,     status: active,   owner: crm@yourco }
  - { code: HERA.CRM.COMMS.WHATSAPP.MESSAGE_SENT.v1,     status: active,   owner: crm@yourco }
  - { code: HERA.CRM.IMPORT.DEAL.v1,              status: active,   owner: data@yourco }
  - { code: HERA.CRM.IMPORT.ROLLBACK.v1,          status: proposed, owner: data@yourco }

