smart_code: HERA.TEST.SCOPE.CRM.MINI.v1
setup: []
teardown: []

cases:
  - name: "Deal stage change event is logged"
    arrange:
      create_transaction_from_file: tests/payloads/opportunity_stage_change.json
      assign_output_to: stage_tx_id
    expect:
      transactions:
        headers:
          - { transaction_type: "crm_oppty_event", status: "posted" }
      report:
        report_code: HERA.CRM.REPORT.PIPELINE_BY_STAGE.CORE.v1
        params: { as_of: "2025-12-31" }
    strict: true

  - name: "Deal closed-won event is logged"
    arrange:
      create_transaction_from_file: tests/payloads/opportunity_closed_won.json
      assign_output_to: won_tx_id
    expect:
      transactions:
        headers:
          - { transaction_type: "crm_oppty_event", status: "posted" }
    strict: true

  - name: "Email sent is recorded as message"
    arrange:
      create_transaction_from_file: tests/payloads/email_sent.json
      assign_output_to: email_tx_id
    expect:
      transactions:
        headers:
          - { transaction_type: "crm_activity", status: "posted" }
    strict: true
