'use client'

/**
 * AP Invoices CRUD Page
 * Generated by HERA Enterprise Generator
 * 
 * Module: FINANCE
 * Entity: AP_INVOICE
 * Smart Code: HERA.FINANCE.TXN.ENTITY.AP_INVOICE.v1
 * Description: Accounts payable invoices for vendor payments
 */

import React, { useState, useCallback, useEffect } from 'react'
import { MobilePageLayout } from '@/components/mobile/MobilePageLayout'
import { MobileFilters, type FilterField } from '@/components/mobile/MobileFilters'
import { MobileDataTable, type TableColumn, type TableRecord } from '@/components/mobile/MobileDataTable'
import { MobileCard } from '@/components/mobile/MobileCard'
import { MobileChart } from '@/components/mobile/MobileCharts'
import { useHERAAuth } from '@/components/auth/HERAAuthProvider'
import { useUniversalEntity } from '@/hooks/useUniversalEntity'
import { 
  AlertCircle,
  CheckCircle,
  Clock,
  Download,
  Edit,
  Eye,
  FileText,
  Filter,
  MoreVertical,
  Plus,
  Save,
  Search,
  Trash2,
  TrendingUp,
  Upload,
  X
} from 'lucide-react'

/**
 * APInvoice Entity Interface
 * Extends TableRecord for HERA compliance
 */
interface APInvoice extends TableRecord {
  id: string
  entity_id?: string
  entity_name: string
  smart_code: string
  status?: string
  
  // Dynamic fields (stored in core_dynamic_data)
  invoice_number?: string
  vendor_id?: string
  invoice_date?: string
  due_date?: string
  total_amount?: string
  status?: string
  reference?: string
  
  // System fields
  created_at?: string
  updated_at?: string
  created_by?: string
  updated_by?: string
  
  // Business rule fields
  
  
}

/**
 * HERA AP Invoice Smart Codes
 * Auto-generated from preset configuration
 */
const AP_INVOICE_SMART_CODES = {
  ENTITY: 'HERA.FINANCE.TXN.ENTITY.AP_INVOICE.v1',
  FIELD_INVOICE_NUMBER: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.INVOICE_NUMBER.V1',
  FIELD_VENDOR_ID: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.VENDOR_ID.V1',
  FIELD_INVOICE_DATE: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.INVOICE_DATE.V1',
  FIELD_DUE_DATE: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.DUE_DATE.V1',
  FIELD_TOTAL_AMOUNT: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.TOTAL_AMOUNT.V1',
  FIELD_STATUS: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.STATUS.V1',
  FIELD_REFERENCE: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.REFERENCE.V1',
  
  // Event smart codes for audit trail
  EVENT_CREATED: 'HERA.FINANCE.TXN.EVENT.AP_INVOICE.v1.CREATED.V1',
  EVENT_UPDATED: 'HERA.FINANCE.TXN.EVENT.AP_INVOICE.v1.UPDATED.V1',
  EVENT_DELETED: 'HERA.FINANCE.TXN.EVENT.AP_INVOICE.v1.DELETED.V1'
} as const

/**
 * AP Invoices Main Page Component
 * Enterprise-grade CRUD with quality gates and business rules
 */
export default function APInvoicesPage() {
  const { currentOrganization, isAuthenticated, user } = useHERAAuth()
  const [selectedAPInvoices, setSelectedAPInvoices] = useState<(string | number)[]>([])
  const [showAddModal, setShowAddModal] = useState(false)
  const [showEditModal, setShowEditModal] = useState(false)
  const [showDeleteModal, setShowDeleteModal] = useState(false)
  const [currentAPInvoice, setCurrentAPInvoice] = useState<APInvoice | null>(null)
  const [ap_invoiceToDelete, setAPInvoiceToDelete] = useState<APInvoice | null>(null)
  const [filters, setFilters] = useState({
    search: '',
    status: '',
    // Dynamic filter fields
    invoice_number: '',
    vendor_id: '',
    invoice_date: ''
  })

  // HERA Universal Entity Integration
  const ap_invoiceData = useUniversalEntity({
    entity_type: 'AP_INVOICE',
    organizationId: currentOrganization?.id,
    filters: {
      include_dynamic: true,
      include_relationships: undefined,
      status: 'active'
    },
    dynamicFields: [
      { name: 'invoice_number', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.INVOICE_NUMBER.V1', required: false },
      { name: 'vendor_id', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.VENDOR_ID.V1', required: false },
      { name: 'invoice_date', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.INVOICE_DATE.V1', required: false },
      { name: 'due_date', type: 'date', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.DUE_DATE.V1', required: false },
      { name: 'total_amount', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.TOTAL_AMOUNT.V1', required: false },
      { name: 'status', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.STATUS.V1', required: false },
      { name: 'reference', type: 'text', smart_code: 'HERA.FINANCE.TXN.DYN.AP_INVOICE.v1.REFERENCE.V1', required: false }
    ]
  })

  // Transform entities with business rule extensions
  const ap_invoices: APInvoice[] = ap_invoiceData.entities?.map((entity: any) => {
    return {
      id: entity.id,
      entity_id: entity.id,
      entity_name: entity.entity_name || '',
      smart_code: entity.smart_code || '',
      status: entity.status || 'active',
      
      // Map dynamic fields with type safety
      invoice_number: entity.dynamic_data?.find((d: any) => d.field_name === 'invoice_number')?.field_value_text || '',
      vendor_id: entity.dynamic_data?.find((d: any) => d.field_name === 'vendor_id')?.field_value_text || '',
      invoice_date: entity.dynamic_data?.find((d: any) => d.field_name === 'invoice_date')?.field_value_text || '',
      due_date: entity.dynamic_data?.find((d: any) => d.field_name === 'due_date')?.field_value_text || '',
      total_amount: entity.dynamic_data?.find((d: any) => d.field_name === 'total_amount')?.field_value_text || '',
      status: entity.dynamic_data?.find((d: any) => d.field_name === 'status')?.field_value_text || '',
      reference: entity.dynamic_data?.find((d: any) => d.field_name === 'reference')?.field_value_text || '',
      
      // System fields
      created_at: entity.created_at,
      updated_at: entity.updated_at,
      created_by: entity.created_by,
      updated_by: entity.updated_by
      
      
    }
  }) || []

  // Enhanced KPI calculations with preset metrics
  const kpis = [
    {
      title: 'Total AP Invoices',
      value: ap_invoices.length.toString(),
      change: '+5.2%',
      trend: 'up' as const,
      icon: FileText
    },
    {
      title: 'Active AP Invoices',
      value: ap_invoices.filter(item => item.status === 'active').length.toString(),
      change: '+2.1%',
      trend: 'up' as const,
      icon: CheckCircle
    },
    {
      title: 'This Month',
      value: ap_invoices.filter(item => {
        if (!item.created_at) return false
        const created = new Date(item.created_at)
        const now = new Date()
        return created.getMonth() === now.getMonth() && created.getFullYear() === now.getFullYear()
      }).length.toString(),
      change: '+8.3%',
      trend: 'up' as const,
      icon: TrendingUp
    }
  ]

  // Enhanced table columns with business rule columns
  const columns: TableColumn[] = [
    { key: 'entity_name', label: 'AP Invoice Name', sortable: true },
    { key: 'invoice_number', label: 'Invoice number', sortable: true },
    { key: 'vendor_id', label: 'Vendor id', sortable: true },
    { key: 'invoice_date', label: 'Invoice date', sortable: true },
    { key: 'due_date', label: 'Due date', sortable: true },
    { key: 'total_amount', label: 'Total amount', sortable: true },
    { key: 'created_at', label: 'Created', sortable: true },
    { key: 'actions', label: 'Actions', sortable: false }
  ]

  // Enhanced filter fields with business rule filters
  const filterFields: FilterField[] = [
    { key: 'search', label: 'Search AP Invoices', type: 'search' },
    { key: 'status', label: 'Status', type: 'select', options: [
      { value: '', label: 'All Status' },
      { value: 'active', label: 'Active' },
      { value: 'inactive', label: 'Inactive' }
    ]},
    { key: 'invoice_number', label: 'Invoice Number', type: 'select', options: [
        { value: '', label: 'All Invoice Numbers' },
        ...Array.from(new Set(ap_invoices.map(item => item.invoice_number).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]},
    { key: 'vendor_id', label: 'Vendor Id', type: 'select', options: [
        { value: '', label: 'All Vendor Ids' },
        ...Array.from(new Set(ap_invoices.map(item => item.vendor_id).filter(Boolean))).map(val => ({ value: val!, label: val! }))
      ]}
  ]

  // Enterprise CRUD Operations with Events
  const handleAddAPInvoice = async (ap_invoiceData: any) => {
    try {
      const result = await ap_invoiceData.create({
        entity_type: 'AP_INVOICE',
        entity_name: ap_invoiceData.entity_name,
        smart_code: AP_INVOICE_SMART_CODES.ENTITY,
        organization_id: currentOrganization?.id
      }, ap_invoiceData)

      // Emit creation event for audit trail
      await ap_invoiceData.emitEvent(AP_INVOICE_SMART_CODES.EVENT_CREATED, {
        entity_id: result.id,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        data: ap_invoiceData
      })

      setShowAddModal(false)
      console.log('✅ AP Invoice created successfully')
    } catch (error) {
      console.error('❌ Error adding ap_invoice:', error)
    }
  }

  const handleEditAPInvoice = async (ap_invoiceData: any) => {
    if (!currentAPInvoice) return
    
    try {
      await ap_invoiceData.update(currentAPInvoice.entity_id!, {
        entity_name: ap_invoiceData.entity_name
      }, ap_invoiceData)

      // Emit update event
      await ap_invoiceData.emitEvent(AP_INVOICE_SMART_CODES.EVENT_UPDATED, {
        entity_id: currentAPInvoice.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        changes: ap_invoiceData
      })

      setShowEditModal(false)
      setCurrentAPInvoice(null)
      console.log('✅ AP Invoice updated successfully')
    } catch (error) {
      console.error('❌ Error updating ap_invoice:', error)
    }
  }

  const handleDeleteAPInvoice = async () => {
    if (!ap_invoiceToDelete) return
    
    try {
      await ap_invoiceData.delete(ap_invoiceToDelete.entity_id!)

      // Emit deletion event
      await ap_invoiceData.emitEvent(AP_INVOICE_SMART_CODES.EVENT_DELETED, {
        entity_id: ap_invoiceToDelete.entity_id!,
        user_id: user?.id,
        timestamp: new Date().toISOString(),
        entity_name: ap_invoiceToDelete.entity_name
      })

      setShowDeleteModal(false)
      setAPInvoiceToDelete(null)
      console.log('✅ AP Invoice deleted successfully')
    } catch (error) {
      console.error('❌ Error deleting ap_invoice:', error)
    }
  }

  
  

  // Enterprise security checks
  if (!isAuthenticated) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-red-500 mx-auto mb-2" />
        <p>Please log in to access AP Invoices.</p>
      </div>
    )
  }

  if (ap_invoiceData.contextLoading) {
    return (
      <div className="p-4 text-center">
        <div className="animate-spin h-8 w-8 border-4 border-blue-500 border-t-transparent rounded-full mx-auto mb-2"></div>
        <p>Loading AP Invoices...</p>
      </div>
    )
  }

  if (!currentOrganization) {
    return (
      <div className="p-4 text-center">
        <AlertCircle className="h-8 w-8 text-yellow-500 mx-auto mb-2" />
        <p>No organization context found. Please select an organization.</p>
      </div>
    )
  }

  return (
    <MobilePageLayout
      title="AP Invoices"
      subtitle={`${ap_invoices.length} total ap_invoices`}
      primaryColor="#dc2626"
      accentColor="#b91c1c"
      showBackButton={false}
    >
      {/* Enterprise KPI Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        {kpis.map((kpi, index) => (
          <MobileCard key={index} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-600 font-medium">{kpi.title}</p>
                <p className="text-2xl font-bold" style={{ color: '#dc2626' }}>{kpi.value}</p>
                <p className={`text-xs font-medium ${kpi.trend === 'up' ? 'text-green-600' : 'text-red-600'}`}>
                  {kpi.change}
                </p>
              </div>
              <kpi.icon className="h-8 w-8 text-gray-400" />
            </div>
          </MobileCard>
        ))}
      </div>

      {/* Enhanced Filters */}
      <MobileFilters
        fields={filterFields}
        values={filters}
        onChange={setFilters}
        className="mb-6"
      />

      {/* Enterprise Data Table */}
      <MobileDataTable
        data={ap_invoices}
        columns={columns}
        selectedRows={selectedAPInvoices}
        onRowSelect={setSelectedAPInvoices}
        onRowClick={(ap_invoice) => {
          setCurrentAPInvoice(ap_invoice)
          setShowEditModal(true)
        }}
        showBulkActions={selectedAPInvoices.length > 0}
        bulkActions={[
          {
            label: 'Delete Selected',
            action: async () => {
              // Bulk delete with events
              for (const id of selectedAPInvoices) {
                await ap_invoiceData.delete(id.toString())
              }
              setSelectedAPInvoices([])
            },
            variant: 'destructive'
          }
        ]}
        mobileCardRender={(ap_invoice) => (
          <MobileCard key={ap_invoice.id} className="p-4 hover:shadow-md transition-shadow">
            <div className="flex justify-between items-start mb-3">
              <div>
                <h3 className="font-semibold text-lg">{ap_invoice.entity_name}</h3>
                
                
              </div>
              <div className="flex space-x-2">
                <button
                  onClick={() => {
                    setCurrentAPInvoice(ap_invoice)
                    setShowEditModal(true)
                  }}
                  className="p-1 text-blue-600 hover:bg-blue-50 rounded"
                >
                  <Edit className="h-4 w-4" />
                </button>
                <button
                  onClick={() => {
                    setAPInvoiceToDelete(ap_invoice)
                    setShowDeleteModal(true)
                  }}
                  className="p-1 text-red-600 hover:bg-red-50 rounded"
                >
                  <Trash2 className="h-4 w-4" />
                </button>
              </div>
            </div>
            
            {/* Dynamic fields display */}
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Invoice Number:</span>{' '}
              {ap_invoice.invoice_number || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Vendor Id:</span>{' '}
              {ap_invoice.vendor_id || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Invoice Date:</span>{' '}
              {ap_invoice.invoice_date || 'N/A'}
            </div>
            <div className="text-sm text-gray-600 mb-1">
              <span className="font-medium">Due Date:</span>{' '}
              {ap_invoice.due_date || 'N/A'}
            </div>
            
            <div className="text-xs text-gray-400 mt-2 pt-2 border-t">
              Created: {ap_invoice.created_at ? new Date(ap_invoice.created_at).toLocaleDateString() : 'N/A'}
            </div>
          </MobileCard>
        )}
      />

      {/* Floating Action Button */}
      <button
        onClick={() => setShowAddModal(true)}
        className="fixed bottom-6 right-6 text-white rounded-full p-4 shadow-lg transition-colors z-50 hover:shadow-xl"
        style={{ backgroundColor: '#dc2626' }}
      >
        <Plus className="h-6 w-6" />
      </button>

      {/* Enterprise Modals */}
      {showAddModal && (
        <APInvoiceModal
          title="Add New AP Invoice"
          isOpen={showAddModal}
          onClose={() => setShowAddModal(false)}
          onSave={handleAddAPInvoice}
          dynamicFields={ap_invoiceData.dynamicFieldsConfig || []}
          businessRules={{"approval_workflow":true,"gl_posting":true,"audit_trail":true}}
        />
      )}

      {showEditModal && currentAPInvoice && (
        <APInvoiceModal
          title="Edit AP Invoice"
          isOpen={showEditModal}
          onClose={() => {
            setShowEditModal(false)
            setCurrentAPInvoice(null)
          }}
          onSave={handleEditAPInvoice}
          initialData={currentAPInvoice}
          dynamicFields={ap_invoiceData.dynamicFieldsConfig || []}
          businessRules={{"approval_workflow":true,"gl_posting":true,"audit_trail":true}}
        />
      )}

      {showDeleteModal && ap_invoiceToDelete && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-lg max-w-md w-full p-6">
            <div className="flex items-center mb-4">
              <AlertCircle className="h-6 w-6 text-red-500 mr-2" />
              <h3 className="text-lg font-semibold">Delete AP Invoice</h3>
            </div>
            <p className="text-gray-600 mb-6">
              Are you sure you want to delete "{ap_invoiceToDelete.entity_name}"? This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-3">
              <button
                onClick={() => {
                  setShowDeleteModal(false)
                  setAPInvoiceToDelete(null)
                }}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50"
              >
                Cancel
              </button>
              <button
                onClick={handleDeleteAPInvoice}
                className="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 flex items-center"
              >
                <Trash2 className="h-4 w-4 mr-2" />
                Delete
              </button>
            </div>
          </div>
        </div>
      )}
    </MobilePageLayout>
  )
}

/**
 * Enterprise AP Invoice Modal Component
 * Enhanced with business rules and validation
 */
interface APInvoiceModalProps {
  title: string
  isOpen: boolean
  onClose: () => void
  onSave: (data: any) => void
  initialData?: APInvoice
  dynamicFields: any[]
  businessRules: any
}

function APInvoiceModal({ 
  title, 
  isOpen, 
  onClose, 
  onSave, 
  initialData, 
  dynamicFields,
  businessRules 
}: APInvoiceModalProps) {
  const [formData, setFormData] = useState(() => {
    const initial: any = { 
      entity_name: initialData?.entity_name || '' 
    }
    
    dynamicFields.forEach(field => {
      initial[field.name] = initialData?.[field.name as keyof APInvoice] || (field.type === 'number' ? 0 : '')
    })
    
    return initial
  })

  const [errors, setErrors] = useState<Record<string, string>>({})
  const [isSubmitting, setIsSubmitting] = useState(false)

  const validateForm = () => {
    const newErrors: Record<string, string> = {}
    
    // Validate required fields
    dynamicFields.forEach(field => {
      if (field.required && !formData[field.name]) {
        newErrors[field.name] = `${field.label || field.name} is required`
      }
    })
    
    // Entity name validation
    if (!formData.entity_name?.trim()) {
      newErrors.entity_name = 'AP Invoice name is required'
    }
    
    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!validateForm()) return
    
    setIsSubmitting(true)
    try {
      await onSave(formData)
    } catch (error) {
      console.error('Form submission error:', error)
    } finally {
      setIsSubmitting(false)
    }
  }

  if (!isOpen) return null

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
      <div className="bg-white rounded-lg max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <div className="flex justify-between items-center mb-6">
            <h3 className="text-xl font-semibold">{title}</h3>
            <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
              <X className="h-6 w-6" />
            </button>
          </div>

          <form onSubmit={handleSubmit} className="space-y-4">
            {/* Entity Name Field */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                AP Invoice Name *
              </label>
              <input
                type="text"
                value={formData.entity_name}
                onChange={(e) => setFormData({ ...formData, entity_name: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.entity_name ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                required
                disabled={isSubmitting}
              />
              {errors.entity_name && (
                <p className="mt-1 text-sm text-red-600">{errors.entity_name}</p>
              )}
            </div>

            {/* Dynamic Fields with Enhanced Validation */}
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Invoice Number 
              </label>
              <input
                type="text"
                value={formData.invoice_number}
                onChange={(e) => setFormData({ ...formData, invoice_number: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.invoice_number ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.invoice_number && (
                <p className="mt-1 text-sm text-red-600">{errors.invoice_number}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Vendor Id 
              </label>
              <input
                type="text"
                value={formData.vendor_id}
                onChange={(e) => setFormData({ ...formData, vendor_id: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.vendor_id ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.vendor_id && (
                <p className="mt-1 text-sm text-red-600">{errors.vendor_id}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Invoice Date 
              </label>
              <input
                type="text"
                value={formData.invoice_date}
                onChange={(e) => setFormData({ ...formData, invoice_date: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.invoice_date ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.invoice_date && (
                <p className="mt-1 text-sm text-red-600">{errors.invoice_date}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Due Date 
              </label>
              <input
                type="date"
                value={formData.due_date}
                onChange={(e) => setFormData({ ...formData, due_date: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.due_date ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.due_date && (
                <p className="mt-1 text-sm text-red-600">{errors.due_date}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Total Amount 
              </label>
              <input
                type="text"
                value={formData.total_amount}
                onChange={(e) => setFormData({ ...formData, total_amount: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.total_amount ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.total_amount && (
                <p className="mt-1 text-sm text-red-600">{errors.total_amount}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Status 
              </label>
              <input
                type="text"
                value={formData.status}
                onChange={(e) => setFormData({ ...formData, status: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.status ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.status && (
                <p className="mt-1 text-sm text-red-600">{errors.status}</p>
              )}
            </div>
            
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Reference 
              </label>
              <input
                type="text"
                value={formData.reference}
                onChange={(e) => setFormData({ ...formData, reference: e.target.value })}
                className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 ${errors.reference ? 'border-red-300 focus:ring-red-500' : 'border-gray-300 focus:ring-blue-500'}`}
                
                disabled={isSubmitting}
              />
              {errors.reference && (
                <p className="mt-1 text-sm text-red-600">{errors.reference}</p>
              )}
            </div>

            {/* Business Rules Info */}
            

            {/* Form Actions */}
            <div className="flex justify-end space-x-3 pt-4 border-t">
              <button
                type="button"
                onClick={onClose}
                disabled={isSubmitting}
                className="px-4 py-2 text-gray-600 border border-gray-300 rounded-md hover:bg-gray-50 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isSubmitting}
                className="px-4 py-2 text-white rounded-md hover:opacity-90 flex items-center disabled:opacity-50"
                style={{ backgroundColor: '#dc2626' }}
              >
                {isSubmitting ? (
                  <>
                    <div className="animate-spin h-4 w-4 border-2 border-white border-t-transparent rounded-full mr-2"></div>
                    Saving...
                  </>
                ) : (
                  <>
                    <Save className="h-4 w-4 mr-2" />
                    Save
                  </>
                )}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  )
}