smart_code: HERA.MFG.MDM.DYNAMIC_KEYS.CORE.v1
items:
  # Product/Component
  - { slug: product.sku,             entity_type: ENTITY, name: "Product SKU",      metadata: { type: "text" } }
  - { slug: product.base_uom,        entity_type: ENTITY, name: "Base UOM",         metadata: { type: "text" } }
  - { slug: component.sku,           entity_type: ENTITY, name: "Component SKU",    metadata: { type: "text" } }
  - { slug: component.base_uom,      entity_type: ENTITY, name: "Base UOM",         metadata: { type: "text" } }

  # Work Center
  - { slug: work_center.capacity_per_hour, entity_type: ENTITY, name: "Capacity per Hour", metadata: { type: "number" } }
  - { slug: work_center.setup_time_min,    entity_type: ENTITY, name: "Setup Time (min)",  metadata: { type: "number" } }

  # Routing/Operation
  - { slug: routing.version,         entity_type: ENTITY, name: "Routing Version",  metadata: { type: "text" } }
  - { slug: operation.sequence,      entity_type: ENTITY, name: "Operation Seq",    metadata: { type: "number" } }
  - { slug: operation.std_cycle_time_min, entity_type: ENTITY, name: "Std Cycle (min)", metadata: { type: "number" } }
  - { slug: operation.yield_percent, entity_type: ENTITY, name: "Yield %",          metadata: { type: "number" } }

  # BOM Component
  - { slug: bom.component_qty,       entity_type: ENTITY, name: "Component Qty",    metadata: { type: "number" } }
